package main

import (
	"syscall"
)

// ════════════════════════════════════════════════════════════
//  Auto-generated by Mocker circle compiler (M4.2)
//  IR-driven codegen — no hardcoded templates
// ════════════════════════════════════════════════════════════

// ===== Simple Node: world (package main) =====
type world struct {
}

func Newworld() *world {
	world_instance := &world{
	}
	return world_instance
}

func(n *world) add_str_hello(words string) string {
	new := (words + " world!")
	return new
}


// ===== Simple Node: hello (package main) =====
type hello struct {
	h string
}

func Newhello() *hello {
	hello_instance := &hello{
		h: "hello",
	}
	w := Newworld()
	
	out_str:=w.add_str_hello(hello_instance.h)

	p:=NewPrintln()
	p.block0(out_str)

	return hello_instance
}

// ===== Simple Node: Println (package stdio) =====
type Println struct {
}

func NewPrintln() *Println {
	Println_instance := &Println{
	}
	return Println_instance
}

func (n *Println) block0(msg string)  {
	nl := "\\n"
	fid := 1
	data := (msg + nl)
	out := Newwrite()
	out.block0(fid, data)
}


// ===== Simple Node: write (package io) =====
type write struct {
}

func Newwrite() *write {
	write_instance := &write{
	}
	return write_instance
}

func (n *write) block0(fid int, data string)  {
	syscall.Write(fid, []byte(data))
}


func main() {
	// 构造函数编排器模式：main() 调用 entry 节点的 NewXxx()
	_ = Newhello()
	
}
