// Package codegen 从合并后的 DFA 生成 Go 词法分析器源码。
//
// 生成的代码是"硬编码"的：DFA 转移表作为 switch/case 嵌入 Tokenize 函数。
// 相比 map[byte][]int 查表，switch 版本更易被 Go 编译器优化（跳转表/二分）。
package codegen

import (
	"fmt"
	"sort"
	"strings"

	"lexical_analysis/internal/dsl"
)

// Generate 把 SpecFile（已含 DFA）编译为 Go 源码字符串。
// 输出包含：Kind/Type 枚举、Token 结构、Tokenize 主函数、接受态表。
func Generate(sf *dsl.SpecFile) (string, error) {
	if sf.Package == "" {
		return "", fmt.Errorf("spec file has empty package name")
	}
	if sf.DFA == nil {
		return "", fmt.Errorf("DFA is nil; run ToDFA() first")
	}
	if sf.DFA.GetNumStates() == 0 {
		return "", fmt.Errorf("DFA has no states")
	}

	var sb strings.Builder

	writeHeader(&sb, sf)
	if err := writeKindEnum(&sb, sf); err != nil {
		return "", err
	}
	if err := writeTypeEnum(&sb, sf); err != nil {
		return "", err
	}
	if err := writeTokenStruct(&sb); err != nil {
		return "", err
	}
	if err := writeIsSpace(&sb); err != nil {
		return "", err
	}
	if err := writeTokenize(&sb, sf); err != nil {
		return "", err
	}
	if err := writeAcceptTable(&sb, sf); err != nil {
		return "", err
	}

	return sb.String(), nil
}

// ────────────────────────────────────────────────────────────
// Header
// ────────────────────────────────────────────────────────────

func writeHeader(sb *strings.Builder, sf *dsl.SpecFile) {
	fmt.Fprintf(sb, "// Code generated by glex. DO NOT EDIT.\n")
	fmt.Fprintf(sb, "//\n")
	fmt.Fprintf(sb, "// Source tokens: %d\n", len(sf.Tokens))
	fmt.Fprintf(sb, "// DFA states:   %d (minimized)\n", sf.DFA.GetNumStates())
	fmt.Fprintf(sb, "// Accepts:      %d\n\n", len(sf.DFA.GetAccepts()))
	fmt.Fprintf(sb, "package %s\n\n", sf.Package)
	fmt.Fprintf(sb, "import \"fmt\"\n\n")
}

// ────────────────────────────────────────────────────────────
// Kind 枚举（type 分类维度）
// ────────────────────────────────────────────────────────────

func writeKindEnum(sb *strings.Builder, sf *dsl.SpecFile) error {
	fmt.Fprintf(sb, "// Kind 分类（type 维度，例如 KW/OP/SEP/ID/NUM/REAL）\n")
	fmt.Fprintf(sb, "type Kind int\n\n")
	fmt.Fprintf(sb, "const (\n")
	fmt.Fprintf(sb, "\tKindInvalid Kind = iota\n")
	for _, t := range sf.Types {
		fmt.Fprintf(sb, "\tKind%s\n", t)
	}
	fmt.Fprintf(sb, ")\n\n")

	fmt.Fprintf(sb, "var kindNames = [...]string{\n")
	fmt.Fprintf(sb, "\tKindInvalid: \"Invalid\",\n")
	for _, t := range sf.Types {
		fmt.Fprintf(sb, "\tKind%s: %q,\n", t, t)
	}
	fmt.Fprintf(sb, "}\n\n")

	fmt.Fprintf(sb, "func (k Kind) String() string { return kindNames[k] }\n\n")
	return nil
}

// ────────────────────────────────────────────────────────────
// Type 枚举（具体 token 维度）
// ────────────────────────────────────────────────────────────

func writeTypeEnum(sb *strings.Builder, sf *dsl.SpecFile) error {
	fmt.Fprintf(sb, "// Type token 名称（具体 token 维度，例如 KW_IF/KW_ELSE/.../ID/NUM/REAL）\n")
	fmt.Fprintf(sb, "type Type int\n\n")
	fmt.Fprintf(sb, "const (\n")
	fmt.Fprintf(sb, "\tTypeInvalid Type = iota\n")
	for _, t1 := range sf.Tokens {
		fmt.Fprintf(sb, "\tType%s\n", t1.Key)
	}
	fmt.Fprintf(sb, ")\n\n")

	fmt.Fprintf(sb, "var typeNames = [...]string{\n")
	fmt.Fprintf(sb, "\tTypeInvalid: \"Invalid\",\n")
	for _, t1 := range sf.Tokens {
		fmt.Fprintf(sb, "\tType%s: %q,\n", t1.Key, t1.Key)
	}
	fmt.Fprintf(sb, "}\n\n")

	fmt.Fprintf(sb, "var typeKinds = [...]Kind{\n")
	fmt.Fprintf(sb, "\tTypeInvalid: KindInvalid,\n")
	for _, t1 := range sf.Tokens {
		fmt.Fprintf(sb, "\tType%s: Kind%s,\n", t1.Key, t1.Type)
	}
	fmt.Fprintf(sb, "}\n\n")

	fmt.Fprintf(sb, "func (t Type) String() string { return typeNames[t] }\n\n")
	return nil
}

// ────────────────────────────────────────────────────────────
// Token 结构
// ────────────────────────────────────────────────────────────

func writeTokenStruct(sb *strings.Builder) error {
	fmt.Fprintf(sb, "// Token 词法分析器输出的最小单元。\n")
	fmt.Fprintf(sb, "type Token struct {\n")
	fmt.Fprintf(sb, "\tType  Type   // token 名称枚举\n")
	fmt.Fprintf(sb, "\tKind  Kind   // type 分类（冗余，方便不用 switch）\n")
	fmt.Fprintf(sb, "\tValue string // 匹配的原始文本\n")
	fmt.Fprintf(sb, "}\n\n")
	fmt.Fprintf(sb, "func (t Token) String() string {\n")
	fmt.Fprintf(sb, "\treturn fmt.Sprintf(\"%%s(%%q)\", t.Type, t.Value)\n")
	fmt.Fprintf(sb, "}\n\n")
	return nil
}

// ────────────────────────────────────────────────────────────
// isSpace
// ────────────────────────────────────────────────────────────

func writeIsSpace(sb *strings.Builder) error {
	fmt.Fprintf(sb, "// isSpace 空白字符（被 Tokenize 自动跳过）\n")
	fmt.Fprintf(sb, "func isSpace(c byte) bool {\n")
	fmt.Fprintf(sb, "\treturn c == ' ' || c == '\\t' || c == '\\n' || c == '\\r'\n")
	fmt.Fprintf(sb, "}\n\n")
	return nil
}

// ────────────────────────────────────────────────────────────
// Tokenize 主函数（硬编码 DFA 转移）
// ────────────────────────────────────────────────────────────

func writeTokenize(sb *strings.Builder, sf *dsl.SpecFile) error {
	fmt.Fprintf(sb, "// Tokenize 把 input 切成 []Token。\n")
	fmt.Fprintf(sb, "// 算法：最长匹配。空白（空格/制表/换行/回车）自动跳过。\n")
	fmt.Fprintf(sb, "// 遇到无法识别的字符返回 error。\n")
	fmt.Fprintf(sb, "func Tokenize(input string) ([]Token, error) {\n")
	fmt.Fprintf(sb, "\tvar tokens []Token\n")
	fmt.Fprintf(sb, "\tpos, start, state := 0, 0, 0\n")
	fmt.Fprintf(sb, "\tlastAcceptPos := -1\n")
	fmt.Fprintf(sb, "\tvar lastAcceptType Type = TypeInvalid\n\n")

	// commit closure: 提交 lastAccept 并 rewind pos
	fmt.Fprintf(sb, "\tcommit := func() bool {\n")
	fmt.Fprintf(sb, "\t\tif lastAcceptPos < 0 {\n")
	fmt.Fprintf(sb, "\t\t\treturn false\n")
	fmt.Fprintf(sb, "\t\t}\n")
	fmt.Fprintf(sb, "\t\ttokens = append(tokens, Token{\n")
	fmt.Fprintf(sb, "\t\t\tType:  lastAcceptType,\n")
	fmt.Fprintf(sb, "\t\t\tKind:  typeKinds[lastAcceptType],\n")
	fmt.Fprintf(sb, "\t\t\tValue: input[start : lastAcceptPos+1],\n")
	fmt.Fprintf(sb, "\t\t})\n")
	fmt.Fprintf(sb, "\t\tpos = lastAcceptPos + 1\n")
	fmt.Fprintf(sb, "\t\tstart = pos\n")
	fmt.Fprintf(sb, "\t\tstate = 0\n")
	fmt.Fprintf(sb, "\t\tlastAcceptPos = -1\n")
	fmt.Fprintf(sb, "\t\tlastAcceptType = TypeInvalid\n")
	fmt.Fprintf(sb, "\t\treturn true\n")
	fmt.Fprintf(sb, "\t}\n\n")

	fmt.Fprintf(sb, "\tfor pos < len(input) {\n")
	fmt.Fprintf(sb, "\t\tch := input[pos]\n")
	fmt.Fprintf(sb, "\t\tif isSpace(ch) {\n")
	fmt.Fprintf(sb, "\t\t\tcommit()\n")
	fmt.Fprintf(sb, "\t\t\tpos++\n")
	fmt.Fprintf(sb, "\t\t\tstart = pos\n")
	fmt.Fprintf(sb, "\t\t\tcontinue\n")
	fmt.Fprintf(sb, "\t\t}\n\n")

	// ── 硬编码 DFA 转移 ──
	fmt.Fprintf(sb, "\t\tnext := -1\n")
	fmt.Fprintf(sb, "\t\tswitch state {\n")

	// 对每个状态生成 case
	dfa := sf.DFA
	for stateID := 0; stateID < dfa.GetNumStates(); stateID++ {
		trans := dfa.GetTrans()[stateID]
		fmt.Fprintf(sb, "\t\tcase %d:\n", stateID)
		if len(trans) == 0 {
			fmt.Fprintf(sb, "\t\t\t// accept (no transitions)\n")
			continue
		}
		// 按目标状态分组
		byTarget := make(map[int][]byte)
		for ch, tos := range trans {
			for _, to := range tos {
				byTarget[to] = append(byTarget[to], ch)
			}
		}
		// 排序目标
		var targets []int
		for to := range byTarget {
			targets = append(targets, to)
		}
		sort.Ints(targets)

		fmt.Fprintf(sb, "\t\t\tswitch {\n")
		for _, to := range targets {
			chars := byTarget[to]
			sort.Slice(chars, func(i, j int) bool { return chars[i] < chars[j] })
			// 拆成 case chunks 便于阅读
			for i := 0; i < len(chars); i += 8 {
				end := i + 8
				if end > len(chars) {
					end = len(chars)
				}
				chunk := chars[i:end]
				conditions := make([]string, 0, len(chunk))
				for _, c := range chunk {
					conditions = append(conditions, fmt.Sprintf("ch == %s", formatChar(c)))
				}
				fmt.Fprintf(sb, "\t\t\tcase %s:\n\t\t\t\tnext = %d\n",
					strings.Join(conditions, " || "), to)
			}
		}
		fmt.Fprintf(sb, "\t\t}\n")
	}

	fmt.Fprintf(sb, "\t\t}\n\n")

	fmt.Fprintf(sb, "\t\tif next < 0 {\n")
	fmt.Fprintf(sb, "\t\t\tif !commit() {\n")
	fmt.Fprintf(sb, "\t\t\t\treturn nil, fmt.Errorf(\"unexpected char %%q at pos %%d\", ch, pos)\n")
	fmt.Fprintf(sb, "\t\t\t}\n")
	fmt.Fprintf(sb, "\t\t\tcontinue\n")
	fmt.Fprintf(sb, "\t\t}\n")
	fmt.Fprintf(sb, "\t\tstate = next\n")
	fmt.Fprintf(sb, "\t\tif typ, ok := accepts[next]; ok {\n")
	fmt.Fprintf(sb, "\t\t\tlastAcceptPos = pos\n")
	fmt.Fprintf(sb, "\t\t\tlastAcceptType = typ\n")
	fmt.Fprintf(sb, "\t\t}\n")
	fmt.Fprintf(sb, "\t\tpos++\n")
	fmt.Fprintf(sb, "\t}\n\n")

	fmt.Fprintf(sb, "\tif !commit() && state != 0 {\n")
	fmt.Fprintf(sb, "\t\treturn nil, fmt.Errorf(\"incomplete token at end of input (pos %%d)\", start)\n")
	fmt.Fprintf(sb, "\t}\n")
	fmt.Fprintf(sb, "\treturn tokens, nil\n")
	fmt.Fprintf(sb, "}\n\n")
	return nil
}

// ────────────────────────────────────────────────────────────
// 接受态表
// ────────────────────────────────────────────────────────────

func writeAcceptTable(sb *strings.Builder, sf *dsl.SpecFile) error {
	fmt.Fprintf(sb, "// accepts 接受态表：stateId → token 名称。\n")
	fmt.Fprintf(sb, "var accepts = map[int]Type{\n")

	// 按 stateId 排序输出
	type pair struct {
		state int
		typ   string
	}
	var entries []pair
	for stateID, tag := range sf.DFA.GetAccepts() {
		entries = append(entries, pair{stateID, tag})
	}
	sort.Slice(entries, func(i, j int) bool { return entries[i].state < entries[j].state })

	for _, e := range entries {
		fmt.Fprintf(sb, "\t%d: Type%s,\n", e.state, e.typ)
	}
	fmt.Fprintf(sb, "}\n")
	return nil
}

// formatChar 把字节格式化为 Go 字面量（用于 switch case）。
func formatChar(c byte) string {
	switch c {
	case '\'':
		return "'\\''"
	case '\\':
		return "'\\\\'"
	case '\t':
		return "'\\t'"
	case '\n':
		return "'\\n'"
	case '\r':
		return "'\\r'"
	case 0:
		return "'\\x00'"
	}
	if c >= 0x20 && c < 0x7f {
		return fmt.Sprintf("%q", c)
	}
	return fmt.Sprintf("'\\x%02x'", c)
}
