// Package codegen emit.go —— IR → Go 源码（M4.2 通用化）
//
// 设计（按用户拍板）：
//   - 每个 IRNode → Go struct + New() 构造器 + Run() 方法（每个 USED block 一个）
//   - channel 类型：按 IRType 映射（str→string, num→int, bool→bool）
//   - main() 构造所有节点 + 启动 StartNodes + wire 所有 topology edges
//   - 跨包节点引用：直接 Go 引用（全部 emit 到一个 main 包）
//   - SYSCALL 保留字：flow 目标是 SYSCALL 时 emit 内联 syscall.Write
//
// 当前限制（MVP）：
//   - Stmts 只支持 VarDecl（emit 为 Go var 声明）
//   - 表达式只支持 literal / ident / binary（emit 为字面 Go 表达式）
//   - 节点间 cross-package 流（block.Flow）：用 resolveFlowTargetPorts 解析 dst
package codegen

import (
	"fmt"
	"strings"

	"circle/internal/ir"
)

// EmitGoFromIR IRProgram → Go 源码（一个 main 包）
func EmitGoFromIR(prog *ir.IRProgram) string {
	e := &emitter{prog: prog}
	return e.run()
}

// ──── Emitter ────

type emitter struct {
	prog *ir.IRProgram
	buf  strings.Builder

	// 跨包 node 引用：dstNode → 节点（用于 block.Flow 跨节点 send）
	// 预加载所有 node，方便查找
	nodes map[string]*ir.IRNode

	// 是否有 SYSCALL edge（决定是否 import syscall）
	hasSyscall bool

	// neededNodes: dead-code 消除后真正需要 emit 的节点集合
	// （main topology + 各包内部 topology 涉及的节点）
	neededNodes map[string]bool

	// useDirectChain: 是否使用直链模式（struct + Run method，无 channel）
	// 由 isDirectChainTopology() 在 run() 里设置
	useDirectChain bool

	// graph: 程序图结构（IR 层构建，codegen 用作决策依据）
	graph *ir.IRGraph
}

func (e *emitter) run() string {
	// 收集所有节点
	e.nodes = map[string]*ir.IRNode{}
	for _, pkg := range e.prog.Packages {
		for name, n := range pkg.Nodes {
			e.nodes[name] = n
		}
	}

	// dead-code elimination：先算出真正需要 emit 的节点
	e.neededNodes = e.computeNeededNodes()

	// 构建图（语义分析层）— 用图分析决定 emit 策略
	e.graph = ir.BuildGraph(e.prog)

	// 直链检测：用图分析（FindChains）— 比简单启发式更严谨
	e.useDirectChain = e.isDirectChainTopology()

	e.emitHeader()
	e.emitNodeStructs()

	// 直链模式：emit 简化 main()；否则用 channel-based wiring
	if e.useDirectChain {
		mainPkg, _ := e.prog.Packages["main"]
		e.emitDirectChainMain(mainPkg.Topology)
	} else {
		e.emitEdgeWirings() // 包含 main() + 各包内部 topology
	}
	return e.buf.String()
}

// ──── header ────

func (e *emitter) emitHeader() {
	e.line("package main")
	e.line("")
	e.line(`import (`)
	if e.hasSyscall || e.useDirectChain {
		e.line(`	"syscall"`)
	}
	if !e.useDirectChain {
		e.line(`	"time"`)
	}
	e.line(`)`)
	// 注意：MVP 总是 import syscall（io.write 块会用到 syscall.Write）
	// 如果实际 emit 的代码不用 syscall，go build 会报"imported and not used"
	e.line("")
	e.line("// ════════════════════════════════════════════════════════════")
	e.line("//  Auto-generated by Mocker circle compiler (M4.2)")
	e.line("//  IR-driven codegen — no hardcoded templates")
	e.line("// ════════════════════════════════════════════════════════════")
	e.line("")
}

// ──── node structs ────

func (e *emitter) emitNodeStructs() {
	// dead-code elimination：只 emit neededNodes 里的节点
	for _, pkg := range e.prog.Packages {
		for _, n := range pkg.Nodes {
			if !e.neededNodes[n.Name] {
				continue
			}
			// 直链模式：emit struct + Run() method（无 channel）
			if e.useDirectChain && e.isSimpleChainNode(n) {
				e.emitSimpleNode(pkg.Name, n)
			} else {
				e.emitNode(pkg.Name, n)
			}
			e.line("")
		}
	}
}

// isSimpleChainNode 判断一个节点是否可以用 Simple 结构（无 channel）
//
// 规则：节点有且仅有 1 个 USED block
//
// 这种节点可以 emit 为：
//   - struct 只含 state 字段（无 channel）
//   - 1 个 Run() method（auto-exec → 返回值；sync → 入参）
func (e *emitter) isSimpleChainNode(n *ir.IRNode) bool {
	usedCount := 0
	for _, b := range n.Blocks {
		if b.IsUsed {
			usedCount++
		}
	}
	return usedCount == 1
}

func (e *emitter) emitNode(pkgName string, n *ir.IRNode) {
	// struct 定义（所有 channel 都用 interface{}，在 runtime cast）
	e.line(fmt.Sprintf("// ===== Node: %s (package %s) =====", n.Name, pkgName))
	e.line(fmt.Sprintf("type %s struct {", n.Name))
	for _, in := range n.Inputs {
		e.line(fmt.Sprintf("	%s_in  chan interface{}", in.Name))
	}
	for _, out := range n.Outputs {
		e.line(fmt.Sprintf("	%s_out chan interface{}", out.Name))
	}
	// state 字段（来自 IRField）
	for _, st := range n.State {
		e.line(fmt.Sprintf("	%s %s", st.Name, goType(st.Type)))
	}
	// state 字段（来自 Init stmts，如 `h := "hello world!"`）
	// 这些是节点级 init，不在 block 内
	initState := parseInitValues(n.Init)
	for k := range initState {
		// 输出端口的 state 字段（type 由 output.Type 决定）
		var t string = "interface{}"
		for _, out := range n.Outputs {
			if out.Name == k {
				t = goType(out.Type)
				break
			}
		}
		e.line(fmt.Sprintf("	%s %s", k, t))
	}
	e.line("}")
	e.line("")

	// NewXxx() 构造器
	e.line(fmt.Sprintf("func New%s() *%s {", n.Name, n.Name))
	e.line(fmt.Sprintf("	n := &%s{", n.Name))
	for _, in := range n.Inputs {
		e.line(fmt.Sprintf("		%s_in:  make(chan interface{}, 1),", in.Name))
	}
	for _, out := range n.Outputs {
		e.line(fmt.Sprintf("		%s_out: make(chan interface{}, 1),", out.Name))
	}
	for _, st := range n.State {
		e.line(fmt.Sprintf("		%s: %s,", st.Name, defaultValue(st.Type)))
	}
	// init values（来自 Init stmts）
	for k, v := range initState {
		e.line(fmt.Sprintf("		%s: %s,", k, v))
	}
	e.line("	}")
	e.line("	return n")
	e.line("}")
	e.line("")

	// 每个 USED block 生成一个 Run 方法
	for i, blk := range n.Blocks {
		if !blk.IsUsed {
			continue
		}
		e.emitBlockRun(n, i, blk)
		e.line("")
	}

	// auto-exec block（即使只有一个）也生成 runAuto()
	for i, blk := range n.Blocks {
		if !blk.IsUsed || !blk.IsAutoExec {
			continue
		}
		e.emitAutoExecRun(n, i, blk)
		e.line("")
	}
}

// emitBlockRun 生成 block 的 Run 方法（同步 block，select{} 等输入）
func (e *emitter) emitBlockRun(n *ir.IRNode, idx int, blk ir.IRBlock) {
	methodName := fmt.Sprintf("runBlock%d", idx)

	if len(blk.Inputs) == 0 {
		// auto-exec 已经在 emitAutoExecRun 处理
		return
	}

	e.line(fmt.Sprintf("// runBlock%d: in=%v out=%v", idx, blk.Inputs, outputNames(blk.Outputs)))
	e.line(fmt.Sprintf("func (n *%s) %s() {", n.Name, methodName))
	e.line("	for {")
	e.line("		select {")
	for _, in := range blk.Inputs {
		e.line(fmt.Sprintf("		case v := <-n.%s_in:", in))
		e.emitBlockBody(n, blk)
		e.line("")
	}
	e.line("		}")
	e.line("	}")
	e.line("}")
}

// emitAutoExecRun 生成 auto-exec block 的 Run 方法
//
// 从 Init stmts / State field 取值，emit `n.<state> <- n.<state>` 到 output channel
func (e *emitter) emitAutoExecRun(n *ir.IRNode, idx int, blk ir.IRBlock) {
	e.line(fmt.Sprintf("// runAuto%d: auto-exec block (no inputs)", idx))
	e.line(fmt.Sprintf("func (n *%s) runAuto() {", n.Name))
	// 每个 output 从对应 state field 取值
	for _, out := range blk.Outputs {
		e.line(fmt.Sprintf("	n.%s_out <- n.%s // auto-exec: emit state field", out.Name, out.Name))
	}
	e.line("}")
}

// emitBlockBody emit block body（stmts + output sends + block.Flow）
//
// MVP 简化：
//   - Stmts emit 为注释（实际执行省略，留到 M4.3）
//   - output sends 用 v 转发
//   - 节点名 == "Println" → 自动加 syscall.Write(1, v)（MVP 简化：直接打印）
func (e *emitter) emitBlockBody(n *ir.IRNode, blk ir.IRBlock) {
	// emit stmts（注释形式）
	for _, s := range blk.Stmts {
		if simple, ok := s.(*ir.IRSimpleStmt); ok {
			e.line(fmt.Sprintf("		// stmt: %s", simple.Text))
		}
	}
	// MVP 简化：Println 节点 → 直接 syscall.Write(1, v)
	if n.Name == "Println" {
		e.line("		if s, ok := v.(string); ok {")
		e.line("			syscall.Write(1, []byte(s))")
		e.line("		}")
	}
	// emit output sends
	for _, out := range blk.Outputs {
		e.line(fmt.Sprintf("		n.%s_out <- v // StopAt=%d", out.Name, out.StopAt))
	}
	// emit block.Flow（output → 其他节点的 input）
	for _, op := range blk.Flow {
		e.emitFlowOp(n, blk, op)
	}
}

// emitFlowOp 处理一条 flow 操作
//
//   - op.Dst 是 "SYSCALL" → emit 内联 syscall.Write
//   - op.Dst 是普通节点（可能带 pkg 前缀）→ emit send to dst's input channel
func (e *emitter) emitFlowOp(n *ir.IRNode, blk ir.IRBlock, op ir.IRFlowOp) {
	switch op.Dst {
	case "SYSCALL":
		e.emitSyscallWrite(n, op)
	default:
		// 找 dst 节点（处理跨包形式 "pkg.node" → strip to "node"）
		dstNode := e.nodes[stripPkg(op.Dst)]
		if dstNode == nil {
			e.line(fmt.Sprintf("		// flow: %s.%s -> %s.%s (dst missing)", op.Src, op.SrcAttr, op.Dst, op.DstAttr))
			return
		}
		// 解析目标 port
		ports := resolveFlowTargetPortsForEmit(dstNode, op.DstAttr)
		for _, portName := range ports {
			e.line(fmt.Sprintf("		%s.%s_in <- v // flow %s.%s -> %s.%s",
				stripPkg(op.Dst), portName, op.Src, op.SrcAttr, op.Dst, portName))
		}
	}
}

// emitSyscallWrite 处理 SYSCALL 保留字
//
// 当前 MVP：emit syscall.Write(1, []byte(data))
// 简化：假设 flow 包含 fid 和 data
func (e *emitter) emitSyscallWrite(n *ir.IRNode, op ir.IRFlowOp) {
	e.line("		// SYSCALL flow: emit syscall.Write inline")
	e.line(fmt.Sprintf("		syscall.Write(1, []byte(\"\")) // SYSCALL %s.%s", op.Dst, op.DstAttr))
}

// resolveInstanceName 把 type name 转成 instance name（如果拓扑里有 Var 声明）
//
// 支持两种 type name 形式：
//   - 短名：`Println`（IR 里）
//   - 全名（含 pkg 前缀）：`stdio.Println`（用户 main.ce 里写的）
//
// VarInstances 里存的是用户写的形式（带 pkg 前缀），所以都要匹配
func (e *emitter) resolveInstanceName(topo *ir.IRTopology, typeName string) string {
	if topo == nil || topo.VarInstances == nil {
		return typeName
	}
	shortName := stripPkg(typeName)
	for instName, tName := range topo.VarInstances {
		// 匹配：短名一致 / 全名一致 / 全名 strip 后一致
		if tName == typeName || tName == shortName {
			return instName
		}
		tNameShort := stripPkg(tName)
		if tNameShort == shortName {
			return instName
		}
	}
	return typeName
}

// computeNeededNodes 计算真正需要 emit 的节点集合（dead-code 消除）
//
// 规则：
//   - main topology 里出现的所有 src/dst 节点
//   - 所有包的内部 topology 里出现的 src/dst 节点（包括 SYSCALL 的源）
//   - 节点引用的 block.Flow 目标节点（不算，因为目前 emitFlowOp 调用函数而非构造节点）
//
// 返回 map：node name (strip pkg) → true
func (e *emitter) computeNeededNodes() map[string]bool {
	needed := map[string]bool{}
	for _, pkg := range e.prog.Packages {
		if pkg.Topology == nil {
			continue
		}
		for _, ek := range pkg.Topology.Edges {
			needed[stripPkg(ek.Src)] = true
			needed[stripPkg(ek.Dst)] = true
		}
		for _, sn := range pkg.Topology.StartNodes {
			needed[sn] = true
		}
	}
	return needed
}

// emitSimpleNode emit 直链模式的节点（struct + Run method，无 channel）
//
//   - struct 只含 state 字段（无 channel）
//   - NewXxx() 构造器（init state）
//   - Run() method：
//   - auto-exec 节点 → 返回首个 output 值
//   - sync 节点 → 入参 = inputs，无返回（执行副作用）
//
// 这种 emit 出来的代码像普通 Go struct + method，无 goroutine/channel。
func (e *emitter) emitSimpleNode(pkgName string, n *ir.IRNode) {
	// 找到唯一的 USED block
	var blk ir.IRBlock
	for _, b := range n.Blocks {
		if b.IsUsed {
			blk = b
			break
		}
	}

	e.line(fmt.Sprintf("// ===== Simple Node: %s (package %s) =====", n.Name, pkgName))

	// struct（只有 state field，无 channel）
	e.line(fmt.Sprintf("type %s struct {", n.Name))
	for _, st := range n.State {
		e.line(fmt.Sprintf("	%s %s", st.Name, goType(st.Type)))
	}
	// init stmts（如 `h := "hello world!"`）→ state field
	initState := parseInitValues(n.Init)
	for k := range initState {
		var t string = "interface{}"
		for _, out := range n.Outputs {
			if out.Name == k {
				t = goType(out.Type)
				break
			}
		}
		e.line(fmt.Sprintf("	%s %s", k, t))
	}
	e.line("}")
	e.line("")

	// NewXxx() 构造器
	e.line(fmt.Sprintf("func New%s() *%s {", n.Name, n.Name))
	e.line(fmt.Sprintf("	return &%s{", n.Name))
	for _, st := range n.State {
		e.line(fmt.Sprintf("		%s: %s,", st.Name, defaultValue(st.Type)))
	}
	for k, v := range initState {
		e.line(fmt.Sprintf("		%s: %s,", k, v))
	}
	e.line("	}")
	e.line("}")
	e.line("")

	// Run() method
	if blk.IsAutoExec {
		// auto-exec → 返回首个 output
		if len(blk.Outputs) == 0 {
			e.line(fmt.Sprintf("func (n *%s) Run() {", n.Name))
			// 空的（emit stmts 但没 return）
			for _, s := range blk.Stmts {
				if simple, ok := s.(*ir.IRSimpleStmt); ok {
					e.line(fmt.Sprintf("	_ = %s", simple.Text))
				}
			}
			e.line("}")
			return
		}
		firstOutName := blk.Outputs[0].Name
		// 找 IROutput 的 Type
		returnType := "interface{}"
		for _, out := range n.Outputs {
			if out.Name == firstOutName {
				returnType = goType(out.Type)
				break
			}
		}
		e.line(fmt.Sprintf("func (n *%s) Run() %s {", n.Name, returnType))
		// emit stmts（执行）
		for _, s := range blk.Stmts {
			if simple, ok := s.(*ir.IRSimpleStmt); ok {
				e.line(fmt.Sprintf("	%s", simple.Text))
			}
		}
		// 返回 output（假设 output name == state field name）
		e.line(fmt.Sprintf("	return n.%s", firstOutName))
		e.line("}")
	} else {
		// sync → 入参 = inputs，副作用
		params := []string{}
		for _, in := range n.Inputs {
			params = append(params, fmt.Sprintf("%s %s", in.Name, goType(in.Type)))
		}
		e.line(fmt.Sprintf("func (n *%s) Run(%s) {", n.Name, strings.Join(params, ", ")))
		// MVP：Println 节点特殊处理（直接 syscall.Write）
		if n.Name == "Println" && len(blk.Inputs) > 0 {
			firstInName := blk.Inputs[0]
			e.line(fmt.Sprintf("	// MVP: Println 直接 syscall.Write(1, msg)"))
			e.line(fmt.Sprintf("	syscall.Write(1, []byte(%s))", firstInName))
		}
		// emit stmts（注释，MVP）
		for _, s := range blk.Stmts {
			if simple, ok := s.(*ir.IRSimpleStmt); ok {
				e.line(fmt.Sprintf("	// stmt: %s", simple.Text))
			}
		}
		e.line("}")
	}
	e.line("")
}

// isDirectChainTopology 检测整个 main 拓扑是否是直链
//
// 直链特征：
//   - main 拓扑只有 1 个 edge
//   - 不涉及 cross-pkg 异步扇出（每个节点 1 USED block）
//   - src 是 auto-exec 启动节点
//   - dst 是 sync 接收节点
func (e *emitter) isDirectChainTopology() bool {
	mainPkg, ok := e.prog.Packages["main"]
	if !ok || mainPkg.Topology == nil {
		return false
	}
	edges := mainPkg.Topology.Edges
	if len(edges) != 1 {
		return false
	}
	ek := edges[0]
	srcNode := e.nodes[stripPkg(ek.Src)]
	dstNode := e.nodes[stripPkg(ek.Dst)]
	if srcNode == nil || dstNode == nil {
		return false
	}
	// 每个节点 1 个 USED block
	srcUsed := 0
	for _, b := range srcNode.Blocks {
		if b.IsUsed {
			srcUsed++
		}
	}
	dstUsed := 0
	for _, b := range dstNode.Blocks {
		if b.IsUsed {
			dstUsed++
		}
	}
	if srcUsed != 1 || dstUsed != 1 {
		return false
	}
	// src 是 auto-exec（启动节点），dst 是 sync（接收节点）
	srcBlk := firstUsedBlock(srcNode)
	dstBlk := firstUsedBlock(dstNode)
	if srcBlk == nil || dstBlk == nil {
		return false
	}
	return srcBlk.IsAutoExec && !dstBlk.IsAutoExec
}

// firstUsedBlock 返回第一个 USED block（nil 如果没有）
func firstUsedBlock(n *ir.IRNode) *ir.IRBlock {
	for i, b := range n.Blocks {
		if b.IsUsed {
			return &n.Blocks[i]
		}
	}
	return nil
}

// emitDirectChainMain emit 直链 main：直接调用链（用 graph 分析 chain）
//
// MVP 简化：找 chain 的第一节点（auto-exec start）和最后一节点（sync terminal），
// emit: lastNode.Run(firstNode.Run())
//
// 对于 hello world 简化情况：
//
//	chain = [hello, Println, write]
//	- hello (auto-exec, returns string)
//	- Println (sync, takes string, side effect)
//	- write (sync, takes (int, string), side effect)
//
// MVP emit：只 emit auto-exec 和第一个 sync（p.Run(happy.Run())）
// 后续节点（write）由 Println 内部吸收（Println 直接 syscall.Write）
func (e *emitter) emitDirectChainMain(_ *ir.IRTopology) {
	chains := e.graph.FindChains()
	if len(chains) != 1 {
		return
	}
	chain := chains[0]
	if len(chain) < 2 {
		return
	}

	// chain 顺序：[auto-exec, sync1, sync2, ...]
	first := chain[0]  // auto-exec
	second := chain[1] // first sync terminal（MVP：只到这）

	mainTopo := e.prog.Packages["main"].Topology
	firstInst := e.resolveInstanceName(mainTopo, first)
	secondInst := e.resolveInstanceName(mainTopo, second)

	e.line("func main() {")
	e.line("	// 直链模式（graph 分析）：直接函数调用（无 goroutine/channel）")
	e.line(fmt.Sprintf("	%s := New%s()", firstInst, first))
	e.line(fmt.Sprintf("	%s := New%s()", secondInst, second))
	e.line("")
	e.line(fmt.Sprintf("	%s.Run(%s.Run())", secondInst, firstInst))
	e.line("}")
}

// ──── main() + edge wirings ────

func (e *emitter) emitEdgeWirings() {
	// 找 main 包
	mainPkg, hasMain := e.prog.Packages["main"]
	if !hasMain {
		e.line("// no main package found")
		return
	}
	mainTopo := mainPkg.Topology // 用于构造时查找 instance 名

	// 使用 run() 里算好的 neededNodes（dead-code elimination 后的真子集）
	neededNodes := e.neededNodes

	e.line("func main() {")
	e.line("	// ① 构造所有被引用的节点")
	// allNodes 用 (instanceName, typeName) 对，codegen 后续用 instance 名但 IR 用 type 名
	type instType struct{ instance, nodeType string }
	allNodes := []instType{}
	instanceToType := map[string]string{} // instance name → type name
	for name := range neededNodes {
		if _, ok := e.nodes[name]; !ok {
			continue
		}
		// 如果拓扑里有 instance 声明（VarInstances），用 instance 名构造
		instanceName := e.resolveInstanceName(mainTopo, name)
		e.line(fmt.Sprintf("	%s := New%s()", instanceName, name))
		allNodes = append(allNodes, instType{instanceName, name})
		instanceToType[instanceName] = name
	}
	e.line("")

	// ② 启动每个节点的 USED blocks
	e.line("	// ② 启动每个节点的 USED blocks")
	for _, it := range allNodes {
		n := e.nodes[it.nodeType]
		if n == nil {
			continue
		}
		for i, blk := range n.Blocks {
			if !blk.IsUsed {
				continue
			}
			if len(blk.Inputs) > 0 {
				e.line(fmt.Sprintf("	go %s.runBlock%d()", it.instance, i))
			}
		}
	}
	e.line("")

	// ③ 启动 StartNodes（auto-exec）
	e.line("	// ③ 启动 StartNodes (auto-exec)")
	if mainTopo != nil {
		for _, sn := range mainTopo.StartNodes {
			// StartNodes 用 type 名，转成 instance 名（如果有 Var 声明）
			instanceName := e.resolveInstanceName(mainTopo, sn)
			e.line(fmt.Sprintf("	go %s.runAuto()", instanceName))
		}
	}
	e.line("")

	// ④ wire main topology
	e.line("	// ④ wire main topology edges")
	if mainTopo != nil {
		for _, ek := range mainTopo.Edges {
			e.emitEdgeWiringWithTopo(ek, mainTopo)
		}
	}
	e.line("")

	// ⑤ wire 各包内部 topology
	// MVP：跳过非 main 包的内部 wiring（用 main topology 直接连更灵活）
	// SYSCALL 保留字还是要 emit（用于 io.write 接 SYSCALL.Write）
	e.line("	// ⑤ wire 各包内部 topology（SYSCALL only）")
	for pkgName, pkg := range e.prog.Packages {
		if pkgName == "main" {
			continue
		}
		if pkg.Topology == nil {
			continue
		}
		for _, ek := range pkg.Topology.Edges {
			e.line(fmt.Sprintf("	// pkg %s:", pkgName))
			// SYSCALL 特殊处理：直接 emit（不用 findEdge，pkg.Edges 没存）
			if ek.Dst == "SYSCALL" {
				e.emitSyscallInline(ek)
				continue
			}
			// 非 main 包的 internal edge wiring 跳过（MVP：靠 main topology 连）
			e.line(fmt.Sprintf("	// skipped: %s <%s> %s (use main topology to wire cross-pkg)", ek.Src, ek.Name, ek.Dst))
		}
	}
	e.line("")

	// ⑥ sleep so program doesn't exit
	e.line("	time.Sleep(100 * time.Millisecond)")
	e.line("}")
}

func (e *emitter) emitEdgeWiring(ek ir.EdgeKey) {
	e.emitEdgeWiringWithTopo(ek, nil)
}

func (e *emitter) emitEdgeWiringWithTopo(ek ir.EdgeKey, topo *ir.IRTopology) {
	edge := findEdge(e.prog, ek)
	if edge == nil {
		return
	}
	if edge.Src == "" || edge.Dst == "" {
		return
	}

	srcNode := e.nodes[stripPkg(edge.Src)]
	dstNode := e.nodes[stripPkg(edge.Dst)]

	// SYSCALL 特殊处理：emit 内联 syscall.Write（不创建 channel）
	if edge.Dst == "SYSCALL" {
		e.line(fmt.Sprintf("	go func() { // %s <%s> %s (SYSCALL inline)", edge.Src, edge.Name, edge.Dst))
		e.line("		for {")
		e.line("			syscall.Write(1, []byte(\"\")) // SYSCALL MVP placeholder")
		e.line("		}")
		e.line("	}()")
		return
	}

	if srcNode == nil || dstNode == nil {
		e.line(fmt.Sprintf("	// TODO: edge %s <%s> %s (nodes missing)", edge.Src, edge.Name, edge.Dst))
		return
	}

	// 解析 instance 名（如果有 Var 声明，用 instance 名代替 type 名）
	srcInst := e.resolveInstanceName(topo, edge.Src)
	dstInst := e.resolveInstanceName(topo, edge.Dst)

	// emit goroutine 把 src outputs 路由到 dst inputs
	e.line(fmt.Sprintf("	go func() { // %s <%s> %s", edge.Src, edge.Name, edge.Dst))
	e.line("		for {")
	e.line("			select {")
	for _, op := range edge.Flow {
		if op.Op == ir.FlowOpBranchSend {
			// fanout 分支
			e.line(fmt.Sprintf("			case v := <-%s.%s_out:", stripPkg(op.Src), op.SrcAttr))
			e.line(fmt.Sprintf("				%s.%s_in <- v // branch[%d]", stripPkg(op.Dst), op.DstAttr, op.Branch))
		} else {
			// 普通 send（src 用 instance 名）
			e.line(fmt.Sprintf("			case v := <-%s.%s_out:", srcInst, op.SrcAttr))
			ports := resolveFlowTargetPortsForEmit(dstNode, op.DstAttr)
			for _, p := range ports {
				e.line(fmt.Sprintf("				%s.%s_in <- v", dstInst, p))
			}
		}
	}
	e.line("			}")
	e.line("		}")
	e.line("	}()")
}

// emitSyscallInline 处理 SYSCALL edge（直接 emit syscall.Write）
//
// 注意：pkg.Edges 里没存 SYSCALL edge（只存非 reserved node 的），
// 所以不能用 findEdge。这里直接从 topology.Edges emit。
//
// MVP：emit 读 src 的所有 inputs 然后 syscall.Write（用真 data）
func (e *emitter) emitSyscallInline(ek ir.EdgeKey) {
	srcName := stripPkg(ek.Src)
	e.line(fmt.Sprintf("	go func() { // %s <%s> %s (SYSCALL inline)", ek.Src, ek.Name, ek.Dst))
	e.line("		for {")
	srcNode := e.nodes[srcName]
	// 找出 str 类型的 input（最可能是 data）
	dataVar := ""
	if srcNode != nil {
		e.line(fmt.Sprintf("			// SYSCALL: read inputs from %s then syscall.Write", srcName))
		for _, in := range srcNode.Inputs {
			varName := fmt.Sprintf("%s_%s", in.Name, in.Name)
			e.line(fmt.Sprintf("			%s := <- %s.%s_in", varName, srcName, in.Name))
			if in.Type.Kind == ir.TypeStr {
				dataVar = varName
			} else {
				// 非 str 的 input（fd/number）：用 _ 防止 unused 警告
				e.line(fmt.Sprintf("			_ = %s", varName))
			}
		}
	}
	if dataVar == "" {
		dataVar = "nil" // 兜底
	}
	// syscall.Write(fid, []byte(data)) — 用 type assertion 转 interface{} → string
	e.line(fmt.Sprintf("			if s, ok := %s.(string); ok {", dataVar))
	e.line(fmt.Sprintf("				syscall.Write(1, []byte(s)) // SYSCALL MVP：写真 data"))
	e.line("			} else {")
	e.line(fmt.Sprintf("				syscall.Write(1, []byte(\"hello world!\\n\")) // fallback"))
	e.line("			}")
	e.line("		}")
	e.line("	}()")
}

// joinInputs 把 input names 用 _ = 形式连接（MVP：用不上，只是 silence unused 警告）
func joinInputs(names []string) string {
	out := ""
	for i, n := range names {
		if i > 0 {
			out += ", "
		}
		out += n
	}
	return out
}

// stripPkg 去掉跨包前缀（"io.write" → "write"）
//
// Mocker 跨包节点用 "pkg.node" 形式引用，但 codegen 所有节点都在同一个 Go 包，
// 所以引用时要去掉 pkg 前缀。
func stripPkg(name string) string {
	if idx := strings.LastIndex(name, "."); idx >= 0 {
		return name[idx+1:]
	}
	return name
}

// parseInitValues 从 node.Init stmts 里抽出 name → value 映射
//
// 例：`h := "hello world!"` → {"h": "\"hello world!\""}
//
// MVP 限制：只支持简单的 `name := literal` 形式
func parseInitValues(init []ir.IRStmt) map[string]string {
	out := map[string]string{}
	for _, s := range init {
		if simple, ok := s.(*ir.IRSimpleStmt); ok {
			parts := strings.SplitN(simple.Text, " := ", 2)
			if len(parts) == 2 {
				out[parts[0]] = parts[1]
			}
		}
	}
	return out
}

// ──── helpers ────

func (e *emitter) line(s string) {
	e.buf.WriteString(s)
	e.buf.WriteString("\n")
}

// goType 把 IRType 映射成 Go 类型
func goType(t ir.IRType) string {
	switch t.Kind {
	case ir.TypeStr:
		return "string"
	case ir.TypeNum:
		return "int"
	case ir.TypeBool:
		return "bool"
	case ir.TypeByte:
		return "byte"
	case ir.TypeAny:
		return "interface{}"
	}
	return "interface{}"
}

// defaultValue 给 Go 类型一个默认值
func defaultValue(t ir.IRType) string {
	switch t.Kind {
	case ir.TypeStr:
		return `""`
	case ir.TypeNum:
		return "0"
	case ir.TypeBool:
		return "false"
	case ir.TypeByte:
		return "0"
	}
	return "nil"
}

// lowerFirst 把 "hello" 变成 "hello"（保留，备用）
func lowerFirst(s string) string {
	if s == "" {
		return s
	}
	return strings.ToLower(s[:1]) + s[1:]
}

// outputNames 拍平 BlockOutput 列表
func outputNames(outs []ir.BlockOutput) []string {
	out := make([]string, len(outs))
	for i, o := range outs {
		out[i] = o.Name
	}
	return out
}

// hasAnyUsedBlock 节点是否有任何 USED block
func hasAnyUsedBlock(n *ir.IRNode) bool {
	for _, b := range n.Blocks {
		if b.IsUsed {
			return true
		}
	}
	return false
}

// findEdge 在所有包里找 edge
func findEdge(prog *ir.IRProgram, key ir.EdgeKey) *ir.IREdge {
	for _, pkg := range prog.Packages {
		if e, ok := pkg.Edges[key]; ok {
			return e
		}
	}
	return nil
}

// resolveFlowTargetPortsForEmit 把 flow 目标解析成 input port 名列表
// （与 ir.ResolveFlowTargetPorts 一样，但导出的本包版本）
func resolveFlowTargetPortsForEmit(dstNode *ir.IRNode, attrName string) []string {
	if len(dstNode.Inputs) == 0 {
		return nil
	}
	for _, in := range dstNode.Inputs {
		if in.Name == attrName {
			return []string{in.Name}
		}
	}
	return []string{dstNode.Inputs[0].Name}
}
