// Package codegen emit.go —— IR → Go 源码（M4.2 通用化）
//
// 设计（按用户拍板）：
//   - 每个 IRNode → Go struct + New() 构造器 + Run() 方法（每个 USED block 一个）
//   - channel 类型：按 IRType 映射（str→string, num→int, bool→bool）
//   - main() 构造所有节点 + 启动 StartNodes + wire 所有 topology edges
//   - 跨包节点引用：直接 Go 引用（全部 emit 到一个 main 包）
//   - SYSCALL 保留字：flow 目标是 SYSCALL 时 emit 内联 syscall.Write
//
// 当前限制（MVP）：
//   - Stmts 只支持 VarDecl（emit 为 Go var 声明）
//   - 表达式只支持 literal / ident / binary（emit 为字面 Go 表达式）
//   - 节点间 cross-package 流（block.Flow）：用 resolveFlowTargetPorts 解析 dst
package codegen

import (
	"fmt"
	"strings"

	"circle/internal/ir"
)

// EmitGoFromIR IRProgram → Go 源码（一个 main 包）
func EmitGoFromIR(prog *ir.IRProgram) string {
	e := &emitter{prog: prog}
	return e.run()
}

// ──── Emitter ────

type emitter struct {
	prog *ir.IRProgram
	buf  strings.Builder

	// 跨包 node 引用：dstNode → 节点（用于 block.Flow 跨节点 send）
	// 预加载所有 node，方便查找
	nodes map[string]*ir.IRNode

	// 是否有 SYSCALL edge（决定是否 import syscall）
	hasSyscall bool

	// neededNodes: dead-code 消除后真正需要 emit 的节点集合
	// （main topology + 各包内部 topology 涉及的节点）
	neededNodes map[string]bool

	// useDirectChain: 是否使用直链模式（struct + Run method，无 channel）
	// 由 isDirectChainTopology() 在 run() 里设置
	useDirectChain bool

	// graph: 程序图结构（IR 层构建，codegen 用作决策依据）
	graph *ir.IRGraph

	// callerMethods: target_node_name → [(caller_name, edge_name)]
	// 记录哪些节点是被某个 caller 通过 SubEdge 调用的（用于命名 caller-specific 方法）。
	// 例：world 被 hello 通过 <add_str> 调用 → callerMethods["world"] = [{"hello", "add_str"}]
	callerMethods map[string][]callerMethodInfo
}

// callerMethodInfo 描述一个 caller → callee 的 SubEdge 调用
type callerMethodInfo struct {
	CallerName string // 调用方的节点名（如 "hello"）
	EdgeName   string // 边名（如 "add_str"）
}

// methodName 构造 caller-specific 方法名
//
// 例：caller="hello", edge="add_str" → "add_str_hello"
func (c callerMethodInfo) methodName() string {
	return c.EdgeName + "_" + c.CallerName
}

func (e *emitter) run() string {
	// 1. collect all nodes (by type name, strip pkg)
	e.nodes = map[string]*ir.IRNode{}
	for _, pkg := range e.prog.Packages {
		for name, n := range pkg.Nodes {
			e.nodes[name] = n
		}
	}
	fmt.Printf("DEBUG run: collected %d nodes\n", len(e.nodes))

	// 2. 收集 callerMethods（哪些节点被某个 caller 通过 SubEdge 调用）
	e.collectCallerMethods()

	// dead-code elimination：先算出真正需要 emit 的节点
	e.neededNodes = e.computeNeededNodes()

	// 构建图（语义分析层）— 用图分析决定 emit 策略
	e.graph = ir.BuildGraph(e.prog)

	// 直链检测：用图分析（FindChains）— 比简单启发式更严谨
	e.useDirectChain = e.isDirectChainTopology()
	fmt.Printf("DEBUG useDirectChain=%v\n", e.useDirectChain)

	e.emitHeader()
	fmt.Printf("DEBUG after emitHeader buf len=%d\n", e.buf.Len())
	e.emitNodeStructs()
	fmt.Printf("DEBUG after emitNodeStructs buf len=%d\n", e.buf.Len())

	// 直链模式：emit 简化 main()；否则用 channel-based wiring
	if e.useDirectChain {
		mainPkg, _ := e.prog.Packages["main"]
		e.emitDirectChainMain(mainPkg.Topology)
	} else {
		e.emitEdgeWirings() // 包含 main() + 各包内部 topology
	}
	return e.buf.String()
}

// ──── header ────

func (e *emitter) emitHeader() {
	e.line("package main")
	e.line("")
	e.line(`import (`)
	// M4.5：只在需要时 import syscall
	//  - hasSyscall 标志在 run() 里根据 EmitNode 中的 SYSCALL 引用设置
	//  - 或 useDirectChain + 节点 body 内有 syscall 引用（Println/write 节点 MVP）
	needsSyscall := e.hasSyscall || e.useDirectChain
	if needsSyscall {
		e.line(`	"syscall"`)
	}
	if !e.useDirectChain {
		e.line(`	"time"`)
	}
	e.line(`)`)
	// 注意：MVP 总是 import syscall（io.write 块会用到 syscall.Write）
	e.line("")
	e.line("// ════════════════════════════════════════════════════════════")
	e.line("//  Auto-generated by Mocker circle compiler (M4.2)")
	e.line("//  IR-driven codegen — no hardcoded templates")
	e.line("// ════════════════════════════════════════════════════════════")
	e.line("")
}

// ──── node structs ────

func (e *emitter) emitNodeStructs() {
	// dead-code elimination：只 emit neededNodes 里的节点
	for _, pkg := range e.prog.Packages {
		for _, n := range pkg.Nodes {
			if !e.neededNodes[n.Name] {
				continue
			}
			// 构造函数编排器模式：所有 needed 节点都用 SimpleNode 模式
			// （struct + NewXxx() 构造器 + blockN() 方法）
			if e.useDirectChain {
				e.emitSimpleNode(pkg.Name, n)
			} else {
				e.emitNode(pkg.Name, n)
			}
			e.line("")
		}
	}
}

// isSimpleChainNode 判断一个节点是否可以用 Simple 结构（无 channel）
//
// 规则：节点有且仅有 1 个 USED block
//
// 这种节点可以 emit 为：
//   - struct 只含 state 字段（无 channel）
//   - 1 个 Run() method（auto-exec → 返回值；sync → 入参）
func (e *emitter) isSimpleChainNode(n *ir.IRNode) bool {
	usedCount := 0
	for _, b := range n.Blocks {
		if b.IsUsed {
			usedCount++
		}
	}
	return usedCount == 1
}

func (e *emitter) emitNode(pkgName string, n *ir.IRNode) {
	// struct 定义（所有 channel 都用 interface{}，在 runtime cast）
	e.line(fmt.Sprintf("// ===== Node: %s (package %s) =====", n.Name, pkgName))
	e.line(fmt.Sprintf("type %s struct {", n.Name))
	for _, in := range n.Inputs {
		e.line(fmt.Sprintf("	%s_in  chan interface{}", in.Name))
	}
	for _, out := range n.Outputs {
		e.line(fmt.Sprintf("	%s_out chan interface{}", out.Name))
	}
	// state 字段（来自 IRField）
	for _, st := range n.State {
		e.line(fmt.Sprintf("	%s %s", st.Name, goType(st.Type)))
	}
	// state 字段（来自 Init stmts，如 `h := "hello world!"`）
	// 这些是节点级 init，不在 block 内
	initState := parseInitValues(n.Init)
	for k := range initState {
		// 输出端口的 state 字段（type 由 output.Type 决定）
		var t string = "interface{}"
		for _, out := range n.Outputs {
			if out.Name == k {
				t = goType(out.Type)
				break
			}
		}
		e.line(fmt.Sprintf("	%s %s", k, t))
	}
	e.line("}")
	e.line("")

	// NewXxx() 构造器
	e.line(fmt.Sprintf("func New%s() *%s {", n.Name, n.Name))
	e.line(fmt.Sprintf("	n := &%s{", n.Name))
	for _, in := range n.Inputs {
		e.line(fmt.Sprintf("		%s_in:  make(chan interface{}, 1),", in.Name))
	}
	for _, out := range n.Outputs {
		e.line(fmt.Sprintf("		%s_out: make(chan interface{}, 1),", out.Name))
	}
	for _, st := range n.State {
		e.line(fmt.Sprintf("		%s: %s,", st.Name, defaultValue(st.Type)))
	}
	// init values（来自 Init stmts）
	for k, v := range initState {
		e.line(fmt.Sprintf("		%s: %s,", k, v))
	}
	e.line("	}")
	e.line("	return n")
	e.line("}")
	e.line("")

	// 每个 USED block 生成一个 Run 方法
	for i, blk := range n.Blocks {
		if !blk.IsUsed {
			continue
		}
		e.emitBlockRun(n, i, blk)
		e.line("")
	}

	// auto-exec block（即使只有一个）也生成 runAuto()
	for i, blk := range n.Blocks {
		if !blk.IsUsed || !blk.IsAutoExec {
			continue
		}
		e.emitAutoExecRun(n, i, blk)
		e.line("")
	}
}

// emitBlockRun 生成 block 的 Run 方法（同步 block，select{} 等输入）
func (e *emitter) emitBlockRun(n *ir.IRNode, idx int, blk ir.IRBlock) {
	methodName := fmt.Sprintf("runBlock%d", idx)

	if len(blk.Inputs) == 0 {
		// auto-exec 已经在 emitAutoExecRun 处理
		return
	}

	e.line(fmt.Sprintf("// runBlock%d: in=%v out=%v", idx, blk.Inputs, outputNames(blk.Outputs)))
	e.line(fmt.Sprintf("func (n *%s) %s() {", n.Name, methodName))
	e.line("	for {")
	e.line("		select {")
	for _, in := range blk.Inputs {
		e.line(fmt.Sprintf("		case v := <-n.%s_in:", in))
		e.emitBlockBody(n, blk)
		e.line("")
	}
	e.line("		}")
	e.line("	}")
	e.line("}")
}

// emitAutoExecRun 生成 auto-exec block 的 Run 方法
//
// 从 Init stmts / State field 取值，emit `n.<state> <- n.<state>` 到 output channel
func (e *emitter) emitAutoExecRun(n *ir.IRNode, idx int, blk ir.IRBlock) {
	e.line(fmt.Sprintf("// runAuto%d: auto-exec block (no inputs)", idx))
	e.line(fmt.Sprintf("func (n *%s) runAuto() {", n.Name))
	// 每个 output 从对应 state field 取值
	for _, out := range blk.Outputs {
		e.line(fmt.Sprintf("	n.%s_out <- n.%s // auto-exec: emit state field", out.Name, out.Name))
	}
	e.line("}")
}

// emitBlockBody emit block body（stmts + output sends + block.Flow）
//
// MVP 简化：
//   - Stmts emit 为注释（实际执行省略，留到 M4.3）
//   - output sends 用 v 转发
//   - 节点名 == "Println" → 自动加 syscall.Write(1, v)（MVP 简化：直接打印）
func (e *emitter) emitBlockBody(n *ir.IRNode, blk ir.IRBlock) {
	// emit stmts（注释形式）
	for _, s := range blk.Stmts {
		if simple, ok := s.(*ir.IRSimpleStmt); ok {
			e.line(fmt.Sprintf("		// stmt: %s", simple.Text))
		}
	}
	// MVP 简化：Println 节点 → 直接 syscall.Write(1, v)
	if n.Name == "Println" {
		e.line("		if s, ok := v.(string); ok {")
		e.line("			syscall.Write(1, []byte(s))")
		e.line("		}")
	}
	// emit output sends
	for _, out := range blk.Outputs {
		e.line(fmt.Sprintf("		n.%s_out <- v // StopAt=%d", out.Name, out.StopAt))
	}
	// emit block.Flow（output → 其他节点的 input）
	for _, op := range blk.Flow {
		e.emitFlowOp(n, blk, op)
	}
}

// emitFlowOp 处理一条 flow 操作
//
//   - op.Dst 是 "SYSCALL" → emit 内联 syscall.Write
//   - op.Dst 是普通节点（可能带 pkg 前缀）→ emit send to dst's input channel
func (e *emitter) emitFlowOp(n *ir.IRNode, blk ir.IRBlock, op ir.IRFlowOp) {
	switch op.Dst {
	case "SYSCALL":
		e.emitSyscallWrite(n, op)
	default:
		// 找 dst 节点（处理跨包形式 "pkg.node" → strip to "node"）
		dstNode := e.nodes[stripPkg(op.Dst)]
		if dstNode == nil {
			e.line(fmt.Sprintf("		// flow: %s.%s -> %s.%s (dst missing)", op.Src, op.SrcAttr, op.Dst, op.DstAttr))
			return
		}
		// 解析目标 port
		ports := resolveFlowTargetPortsForEmit(dstNode, op.DstAttr)
		for _, portName := range ports {
			e.line(fmt.Sprintf("		%s.%s_in <- v // flow %s.%s -> %s.%s",
				stripPkg(op.Dst), portName, op.Src, op.SrcAttr, op.Dst, portName))
		}
	}
}

// emitSyscallWrite 处理 SYSCALL 保留字
//
// 当前 MVP：emit syscall.Write(1, []byte(data))
// 简化：假设 flow 包含 fid 和 data
func (e *emitter) emitSyscallWrite(n *ir.IRNode, op ir.IRFlowOp) {
	e.line("		// SYSCALL flow: emit syscall.Write inline")
	e.line(fmt.Sprintf("		syscall.Write(1, []byte(\"\")) // SYSCALL %s.%s", op.Dst, op.DstAttr))
}

// resolveInstanceName 把 type name 转成 instance name（如果拓扑里有 Var 声明）
//
// 支持两种 type name 形式：
//   - 短名：`Println`（IR 里）
//   - 全名（含 pkg 前缀）：`stdio.Println`（用户 main.ce 里写的）
//
// VarInstances 里存的是用户写的形式（带 pkg 前缀），所以都要匹配
func (e *emitter) resolveInstanceName(topo *ir.IRTopology, typeName string) string {
	if topo == nil || topo.VarInstances == nil {
		return typeName
	}
	shortName := stripPkg(typeName)
	for instName, tName := range topo.VarInstances {
		// 匹配：短名一致 / 全名一致 / 全名 strip 后一致
		if tName == typeName || tName == shortName {
			return instName
		}
		tNameShort := stripPkg(tName)
		if tNameShort == shortName {
			return instName
		}
	}
	return typeName
}

// computeNeededNodes 计算真正需要 emit 的节点集合（dead-code 消除）
//
// 规则：
//   - main topology 里出现的所有 src/dst 节点
//   - main topology VarInstances（entry 节点 + 所有 sub-instance 引用）
//   - 所有包的内部 topology 里出现的 src/dst 节点（包括 SYSCALL 的源）
//   - 节点 body 内的 SubInstances（递归收集 sub-graph 引用）
//
// 返回 map：node name (strip pkg) → true
func (e *emitter) computeNeededNodes() map[string]bool {
	needed := map[string]bool{}
	var queue []string

	// 第一轮：从 main topology + VarInstances 开始
	for _, pkg := range e.prog.Packages {
		if pkg.Topology == nil {
			continue
		}
		for _, ek := range pkg.Topology.Edges {
			needed[stripPkg(ek.Src)] = true
			queue = append(queue, stripPkg(ek.Src))
			needed[stripPkg(ek.Dst)] = true
			queue = append(queue, stripPkg(ek.Dst))
		}
		for _, sn := range pkg.Topology.StartNodes {
			needed[sn] = true
			queue = append(queue, sn)
		}
		for _, typeName := range pkg.Topology.VarInstances {
			tn := stripPkg(typeName)
			if !needed[tn] {
				needed[tn] = true
				queue = append(queue, tn)
			}
		}
	}

	// 第二轮：BFS 沿 sub-graph 收集
	for len(queue) > 0 {
		cur := queue[0]
		queue = queue[1:]
		n := e.nodes[cur]
		if n == nil {
			continue
		}
		for _, si := range n.SubInstances {
			tn := stripPkg(si.TypeName)
			if !needed[tn] {
				needed[tn] = true
				queue = append(queue, tn)
			}
		}
	}
	return needed
}

// emitSimpleNode emit 构造函数编排器模式的节点
//
// 设计原则（参考 000-example.go）：
//   - struct 只含 state 字段（无 channel）
//   - NewXxx() 构造器 = init state + orchestration（创建下游 + 调下游方法）
//   - sync block → emit 为 `blockN(inputs...)` method
//   - auto-exec block → 编排逻辑在 NewXxx() 内部（构造时即跑）
//   - main() 只调用 entry 节点的 NewXxx()
//
// 例子（hello world）：
//
//	type hello struct { h string }
//	func Newhello() *hello {
//	    hello_instance := &hello{h: "hello world!"}
//	    p := NewPrintln()             // 创建下游
//	    p.block0(hello_instance.h)   // 调下游的 sync block
//	    return hello_instance
//	}
//
//	type Println struct {}
//	func NewPrintln() *Println { return &Println{} }
//	func (n *Println) block0(msg string) {
//	    syscall.Write(1, []byte(msg))
//	}
//
// emitSimpleNode emit 构造函数编排器模式的节点（M4.5）
//
// 设计：
//   - struct 只含 state 字段（无 channel）
//   - NewXxx() 构造器 = init state + orchestration
//   - sync block → emit 为 `blockN(inputs...)` method（默认）；但若该节点被 caller
//     通过 SubEdge 调用，则 emit caller-specific 方法（`<edge>_<caller>`），不 emit block0
//   - auto-exec block → 编排逻辑在 NewXxx() 内部（构造时即跑）
//
// **Self-contained sync block** 检测：
//   - sync block 的所有 input 都由 SubEdge.RetAttr 充填 → 编排可全部在 NewXxx() 完成，跳过 block0
//   - 否则 → emit block0（外部 caller 负责填输入）
//
// 编排用节点自己的 SubInstances / SubEdges / SubFlows（从 AST 的 sub-graph lower 而来）。
func (e *emitter) emitSimpleNode(pkgName string, n *ir.IRNode) {
	fmt.Printf("DEBUG emitSimpleNode %s: SubFlows=%d SubInstances=%d SubEdges=%d\n",
		n.Name, len(n.SubFlows), len(n.SubInstances), len(n.SubEdges))
	// 找到唯一的 USED block
	var blk ir.IRBlock
	for _, b := range n.Blocks {
		if b.IsUsed {
			blk = b
			break
		}
	}

	e.line(fmt.Sprintf("// ===== Simple Node: %s (package %s) =====", n.Name, pkgName))

	// 1. struct（只有 state field，无 channel）
	e.line(fmt.Sprintf("type %s struct {", n.Name))
	stateFieldNames := map[string]bool{}
	for _, st := range n.State {
		e.line(fmt.Sprintf("	%s %s", st.Name, goType(st.Type)))
		stateFieldNames[st.Name] = true
	}
	// init stmts（如 `h := "hello"`）→ state field（如果还没在 n.State 里）
	initState := parseInitValues(n.Init)
	for k := range initState {
		if stateFieldNames[k] {
			continue // 已存在，避免重复
		}
		var t string = "interface{}"
		for _, out := range n.Outputs {
			if out.Name == k {
				t = goType(out.Type)
				break
			}
		}
		e.line(fmt.Sprintf("	%s %s", k, t))
		stateFieldNames[k] = true
	}
	e.line("}")
	e.line("")

	// 2. NewXxx() 构造器（编排器）
	e.line(fmt.Sprintf("func New%s() *%s {", n.Name, n.Name))

	// 2a. Init state
	blockInitValues := map[string]string{}
	for _, s := range n.Init {
		if simple, ok := s.(*ir.IRSimpleStmt); ok && simple.Kind == "vardecl" {
			parts := strings.SplitN(simple.Text, " := ", 2)
			if len(parts) == 2 {
				blockInitValues[strings.TrimSpace(parts[0])] = strings.TrimSpace(parts[1])
			}
		}
	}
	for _, b := range n.Blocks {
		for _, s := range b.Stmts {
			if simple, ok := s.(*ir.IRSimpleStmt); ok && simple.Kind == "vardecl" {
				parts := strings.SplitN(simple.Text, " := ", 2)
				if len(parts) == 2 {
					blockInitValues[strings.TrimSpace(parts[0])] = strings.TrimSpace(parts[1])
				}
			}
		}
	}

	instanceVarName := n.Name + "_instance"
	e.line(fmt.Sprintf("	%s := &%s{", instanceVarName, n.Name))
	emittedFields := map[string]bool{}
	for _, st := range n.State {
		val := defaultValue(st.Type)
		if initVal, ok := blockInitValues[st.Name]; ok {
			val = initVal
		}
		e.line(fmt.Sprintf("		%s: %s,", st.Name, val))
		emittedFields[st.Name] = true
	}
	for k, v := range initState {
		if emittedFields[k] {
			continue
		}
		e.line(fmt.Sprintf("		%s: %s,", k, v))
		emittedFields[k] = true
	}
	e.line("	}")

	// 2b. 检测该节点是否被 caller 通过 SubEdge 调用
	callerInfos := e.callerMethods[n.Name]

	// 2c. 检测 self-contained sync block（所有 inputs 都由 SubEdge.RetAttr 充填）
	selfContainedSync := false
	if !blk.IsAutoExec && len(blk.Inputs) > 0 && len(n.SubEdges) > 0 {
		// 检查每个 input 都有 SubEdge.RetAttr 充填
		inputCovered := map[string]bool{}
		for _, se := range n.SubEdges {
			if se.RetAttr != "" {
				inputCovered[se.RetAttr] = true
			}
		}
		allCovered := true
		for _, in := range n.Inputs {
			if !inputCovered[in.Name] {
				allCovered = false
				break
			}
		}
		selfContainedSync = allCovered
	}

	// 2d. auto-exec block：按原始顺序 emit stmts
	if blk.IsAutoExec {
		for _, s := range blk.Stmts {
			if simple, ok := s.(*ir.IRSimpleStmt); ok {
				e.line(fmt.Sprintf("	%s", simple.Text))
			}
		}
	}

	// 2e. 编排 SubEdges（不管 auto-exec 还是 sync，全部在 NewXxx 里执行）
	subEdgeResults := map[string]string{} // SrcAttr → 返回值变量名
	e.emitSubEdgesInConstructor(n, subEdgeResults, instanceVarName)

	// 2f. 编排 SubFlows（self-contained sync 或 auto-exec 时在 NewXxx 里执行；
	//      普通 sync block 时在 block0 里执行）
	if blk.IsAutoExec || selfContainedSync {
		e.emitSubFlowsInConstructor(n, subEdgeResults, instanceVarName)
	}

	e.line(fmt.Sprintf("	return %s", instanceVarName))
	e.line("}")
	e.line("")

	// 3. emit 方法
	//   - 被 caller 通过 SubEdge 调用 → emit caller-specific 方法（不 emit block0）
	//   - self-contained sync（inputs 全由 SubEdge 充填）→ 不 emit block0
	//   - 否则 → emit block0
	if len(callerInfos) > 0 {
		// 被多个 caller 通过 SubEdge 调用：emit 多个 caller-specific 方法
		for _, ci := range callerInfos {
			e.emitBlockAsCallerMethod(n, blk, ci, blockInitValues)
		}
	} else if !selfContainedSync && !blk.IsAutoExec {
		// 普通 sync block：emit block0
		e.emitBlockAsDefault(n, blk, blockInitValues)
	}
}

// emitBlockAsCallerMethod 把节点 block emit 为 caller-specific 方法（SubEdge callee）
//
// 例：world 被 hello 通过 <add_str> 调用 → emit add_str_hello(words string) string
func (e *emitter) emitBlockAsCallerMethod(n *ir.IRNode, blk ir.IRBlock, ci callerMethodInfo, blockInitValues map[string]string) {
	methodName := ci.methodName()

	// 参数：节点的 input ports（按顺序）
	params := []string{}
	for _, in := range n.Inputs {
		params = append(params, fmt.Sprintf("%s %s", in.Name, goType(in.Type)))
	}

	// 返回类型：节点的首个 output 类型
	returnType := ""
	if len(blk.Outputs) > 0 {
		firstOut := blk.Outputs[0].Name
		for _, out := range n.Outputs {
			if out.Name == firstOut {
				returnType = goType(out.Type)
				break
			}
		}
		if returnType == "" || returnType == "interface{}" {
			// fallback：看 block 里的 init expr
			if initVal, ok := blockInitValues[firstOut]; ok {
				if strings.Contains(initVal, "+") {
					returnType = "string"
				}
			}
			if returnType == "" || returnType == "interface{}" {
				returnType = "string"
			}
		}
	}

	// caller-specific 方法定义
	e.line(fmt.Sprintf("func(n *%s) %s(%s) %s {", n.Name, methodName, strings.Join(params, ", "), returnType))

	// emit block stmts
	for _, s := range blk.Stmts {
		if simple, ok := s.(*ir.IRSimpleStmt); ok {
			e.line(fmt.Sprintf("	%s", simple.Text))
		}
	}

	// emit SubFlows（如果有，block0 内调用 sub-instance 方法）
	e.emitSubFlows(n, nil, "n")

	// emit return（如果有 return type）
	if returnType != "" && len(blk.Outputs) > 0 {
		e.line(fmt.Sprintf("	return %s", blk.Outputs[0].Name))
	}
	e.line("}")
	e.line("")
}

// emitBlockAsDefault 把节点 block emit 为 block0 方法（默认 sync 入口）
//
// 适用：节点没有被 caller 通过 SubEdge 调用，且不是 self-contained sync block
func (e *emitter) emitBlockAsDefault(n *ir.IRNode, blk ir.IRBlock, blockInitValues map[string]string) {
	params := []string{}
	for _, in := range n.Inputs {
		params = append(params, fmt.Sprintf("%s %s", in.Name, goType(in.Type)))
	}
	returnType := ""
	hasSubFlows := len(n.SubFlows) > 0
	if len(blk.Outputs) > 0 && !hasSubFlows {
		firstOut := blk.Outputs[0].Name
		for _, out := range n.Outputs {
			if out.Name == firstOut {
				returnType = goType(out.Type)
				break
			}
		}
		if returnType == "" || returnType == "interface{}" {
			if initVal, ok := blockInitValues[firstOut]; ok {
				if strings.Contains(initVal, "+") {
					returnType = "string"
				}
			}
			if returnType == "" || returnType == "interface{}" {
				returnType = "string"
			}
		}
	}
	e.line(fmt.Sprintf("func (n *%s) block0(%s) %s {", n.Name, strings.Join(params, ", "), returnType))

	for _, s := range blk.Stmts {
		if simple, ok := s.(*ir.IRSimpleStmt); ok {
			e.line(fmt.Sprintf("	%s", simple.Text))
		}
	}

	e.emitSubFlows(n, nil, "n")

	if returnType != "" && len(blk.Outputs) > 0 {
		e.line(fmt.Sprintf("	return %s", blk.Outputs[0].Name))
	}
	e.line("}")
	e.line("")
}

// emitSubFlows emit SubFlow 调用（在 NewXxx 或 block0 里）
//
// subEdgeResults: SubEdge 的返回值映射（SrcAttr → 返回值变量名）
// selfRef: 引用当前节点的方式（"n" 或 "hello_instance"）
func (e *emitter) emitSubFlows(n *ir.IRNode, subEdgeResults map[string]string, selfRef string) {
	dstCalls := map[string][]string{} // dstInstance → [srcArg1, srcArg2, ...]
	dstOrder := []string{}
	for _, sf := range n.SubFlows {
		if _, exists := dstCalls[sf.DstInstance]; !exists {
			dstOrder = append(dstOrder, sf.DstInstance)
		}
		// 源参数：
		//   优先用 SubEdge 结果（构造函数里的结果变量）
		//   否则：selfRef == "n" 时直接用变量名（block-local）
		//         selfRef == "xxx_instance" 时用 selfRef.SrcAttr（state field）
		srcArg := sf.SrcAttr
		if subEdgeResults != nil {
			if result, ok := subEdgeResults[sf.SrcAttr]; ok {
				srcArg = result
			} else if selfRef != "n" {
				srcArg = fmt.Sprintf("%s.%s", selfRef, sf.SrcAttr)
			}
		} else if selfRef != "n" {
			srcArg = fmt.Sprintf("%s.%s", selfRef, sf.SrcAttr)
		}
		// M4.5：SubFlow 源是 block-input port 时（如 `out_str >> p.msg` 其中 out_str 是 hello 的入度）
		//   此时 selfRef = "n"（在 block0 里），用直接变量名 out_str 即可
		//   但如果 SubFlow 是在 NewXxx 里 emit，且源是 input port，需要从 NewXxx 接收
		//   简单起见：srcArg = sf.SrcAttr（MVP：先支持 input port 作为 SubFlow source）
		dstCalls[sf.DstInstance] = append(dstCalls[sf.DstInstance], srcArg)
	}
	for _, dstInst := range dstOrder {
		srcAttrs := dstCalls[dstInst]
		// 特殊处理 SYSCALL 保留字
		if dstInst == "SYSCALL" || dstInst == "syscall" {
			if len(srcAttrs) >= 2 {
				e.line(fmt.Sprintf("	syscall.Write(%s, []byte(%s))", srcAttrs[0], srcAttrs[1]))
			} else if len(srcAttrs) == 1 {
				e.line(fmt.Sprintf("	syscall.Write(1, []byte(%s))", srcAttrs[0]))
			}
			continue
		}
		// 找 dst type
		var dstType string
		for _, si := range n.SubInstances {
			if si.InstanceName == dstInst {
				dstType = si.TypeName
				if idx := strings.LastIndex(dstType, "."); idx >= 0 {
					dstType = dstType[idx+1:]
				}
				break
			}
		}
		if dstType == "" {
			continue
		}
		e.line(fmt.Sprintf("	%s := New%s()", dstInst, dstType))
		e.line(fmt.Sprintf("	%s.block0(%s)", dstInst, strings.Join(srcAttrs, ", ")))
	}
}

// emitSubEdgesInConstructor 在 NewXxx 里 emit SubEdge 调用（M4.5 重构）
//
// 生成模式：
//   - 创建 callee 实例：`w := Newworld()`
//   - 调 callee 的 caller-specific 方法：`out_str := w.add_str_hello(hello_instance.h)`
//   - 返回值赋给 subEdge.RetAttr（如果为空则 fallback 到 SrcAttr）
//
// 参数：
//   - subEdgeResults: SrcAttr → 返回值变量名映射（供后续 SubFlow 使用）
//   - selfRef: 当前节点的实例变量名（如 "hello_instance"），用于 state field 引用
func (e *emitter) emitSubEdgesInConstructor(n *ir.IRNode, subEdgeResults map[string]string, selfRef string) {
	for _, subEdge := range n.SubEdges {
		// 隐式 SubEdge 推断失败保护：IR 阶段如果不能唯一推断出 SrcAttr，
		// 会标记为 "__implicit__"。此时不 emit（避免生成不合法代码），
		// 输出一个明确的诊断信息，让用户补上显式源。
		if subEdge.SrcAttr == "__implicit__" {
			e.line(fmt.Sprintf("	// ERROR: implicit SubEdge <%s> %s could not infer source",
				subEdge.EdgeName, subEdge.DstInstance))
			e.line(fmt.Sprintf("	// HINT: change '<%s> %s' to 'X <%s> %s' (specify source explicitly)",
				subEdge.EdgeName, subEdge.DstInstance, subEdge.EdgeName, subEdge.DstInstance))
			continue
		}

		// 找 callee type（strip pkg 前缀）
		var dstType string
		for _, si := range n.SubInstances {
			if si.InstanceName == subEdge.DstInstance {
				dstType = stripPkg(si.TypeName)
				break
			}
		}
		if dstType == "" {
			continue
		}

		// 创建 callee 实例
		e.line(fmt.Sprintf("	%s := New%s()", subEdge.DstInstance, dstType))

		// 构造 callee 方法名（caller-specific：<edge>_<caller>）
		methodName := subEdge.EdgeName + "_" + n.Name

		// 决定调用参数：
		//   - 优先看 subEdge.SrcAttr 是 state field 还是 input port
		//   - state field → selfRef.SrcAttr
		//   - input port → 局部变量名（取 SrcAttr）
		//   - 其他（来自前面 SubEdge 的结果）→ subEdgeResults[SrcAttr]
		argExpr := e.subEdgeArgExpr(n, subEdge, selfRef, subEdgeResults)

		// 决定返回值变量名：
		//   - 优先 subEdge.RetAttr（从 top-level edge body 推断）
		//   - fallback：subEdge.SrcAttr（如果 SrcAttr 是 input port name）
		retVar := subEdge.RetAttr
		if retVar == "" {
			// 尝试 fallback：SrcAttr 是 input port name
			isInput := false
			for _, in := range n.Inputs {
				if in.Name == subEdge.SrcAttr {
					isInput = true
					break
				}
			}
			if isInput {
				retVar = subEdge.SrcAttr
			} else {
				retVar = subEdge.SrcAttr + "_result"
			}
		}

		// emit 调用
		e.line(fmt.Sprintf("	%s := %s.%s(%s)", retVar, subEdge.DstInstance, methodName, argExpr))
		subEdgeResults[subEdge.SrcAttr] = retVar
		if subEdge.RetAttr != "" && subEdge.RetAttr != subEdge.SrcAttr {
			subEdgeResults[subEdge.RetAttr] = retVar
		}
	}
}

// subEdgeArgExpr 推断 SubEdge 调用的参数表达式
//
// 优先顺序：
//  1. 如果 SrcAttr 是 state field → selfRef.SrcAttr（如 "hello_instance.h"）
//  2. 如果 SrcAttr 是 input port name → SrcAttr（block 内局部变量）
//  3. 如果前面 SubEdge 产生这个 SrcAttr → subEdgeResults[SrcAttr]
//  4. fallback：SrcAttr（裸名）
func (e *emitter) subEdgeArgExpr(n *ir.IRNode, se *ir.IRSubEdge, selfRef string, subEdgeResults map[string]string) string {
	// 检查是否 state field
	isState := false
	for _, st := range n.State {
		if st.Name == se.SrcAttr {
			isState = true
			break
		}
	}
	if isState {
		return fmt.Sprintf("%s.%s", selfRef, se.SrcAttr)
	}
	// 检查是否是前面 SubEdge 的结果
	if v, ok := subEdgeResults[se.SrcAttr]; ok {
		return v
	}
	// fallback：裸 SrcAttr
	return se.SrcAttr
}

// emitSubFlowsInConstructor 在 NewXxx 里 emit SubFlow 调用（编排后续 sub-instance）
//
// 与 block0 里的 emitSubFlows 区别：
//   - 在 NewXxx 里调用 selfRef 是 instance var（如 "hello_instance"）
//   - 优先使用 subEdgeResults 作为源（因为 SubEdge 产生了局部变量）
func (e *emitter) emitSubFlowsInConstructor(n *ir.IRNode, subEdgeResults map[string]string, selfRef string) {
	dstCalls := map[string][]string{} // dstInstance → [srcArg1, srcArg2, ...]
	dstOrder := []string{}
	for _, sf := range n.SubFlows {
		if _, exists := dstCalls[sf.DstInstance]; !exists {
			dstOrder = append(dstOrder, sf.DstInstance)
		}
		// 源参数：
		//   优先用 SubEdge 结果（构造时产生的局部变量）
		//   否则：若 SrcAttr 是 state field → selfRef.SrcAttr
		//   否则：裸 SrcAttr
		srcArg := sf.SrcAttr
		if v, ok := subEdgeResults[sf.SrcAttr]; ok {
			srcArg = v
		} else {
			isState := false
			for _, st := range n.State {
				if st.Name == sf.SrcAttr {
					isState = true
					break
				}
			}
			if isState {
				srcArg = fmt.Sprintf("%s.%s", selfRef, sf.SrcAttr)
			}
		}
		dstCalls[sf.DstInstance] = append(dstCalls[sf.DstInstance], srcArg)
	}
	for _, dstInst := range dstOrder {
		srcAttrs := dstCalls[dstInst]
		// SYSCALL 特殊处理
		if dstInst == "SYSCALL" || dstInst == "syscall" {
			if len(srcAttrs) >= 2 {
				e.line(fmt.Sprintf("	syscall.Write(%s, []byte(%s))", srcAttrs[0], srcAttrs[1]))
			} else if len(srcAttrs) == 1 {
				e.line(fmt.Sprintf("	syscall.Write(1, []byte(%s))", srcAttrs[0]))
			}
			continue
		}
		// 找 dst type
		var dstType string
		for _, si := range n.SubInstances {
			if si.InstanceName == dstInst {
				dstType = stripPkg(si.TypeName)
				break
			}
		}
		if dstType == "" {
			continue
		}
		e.line(fmt.Sprintf("	%s := New%s()", dstInst, dstType))
		e.line(fmt.Sprintf("	%s.block0(%s)", dstInst, strings.Join(srcAttrs, ", ")))
	}
}

// downstreamCallInfo 构造函数编排用的下游节点信息
type downstreamCallInfo struct {
	downstreamType string
	instanceVar    string
	inputArg       string
}

// findDownstreamCalls 找到当前节点在 main 拓扑里需要调用的下游节点
func (e *emitter) findDownstreamCalls(currentType string) []downstreamCallInfo {
	if e.prog == nil {
		return nil
	}
	mainPkg, ok := e.prog.Packages["main"]
	if !ok || mainPkg.Topology == nil {
		return nil
	}
	var result []downstreamCallInfo
	for _, ie := range mainPkg.Topology.InstanceEdges {
		srcType, srcOk := mainPkg.Topology.VarInstances[ie.SrcInstance]
		if !srcOk {
			continue
		}
		srcTypeShort := srcType
		if idx := strings.LastIndex(srcType, "."); idx >= 0 {
			srcTypeShort = srcType[idx+1:]
		}
		if srcTypeShort != currentType {
			continue
		}

		dstType, dstOk := mainPkg.Topology.VarInstances[ie.DstInstance]
		if !dstOk {
			continue
		}
		dstTypeShort := dstType
		if idx := strings.LastIndex(dstType, "."); idx >= 0 {
			dstTypeShort = dstType[idx+1:]
		}

		inputArg := e.findCurrentOutputField(currentType)
		if inputArg == "" {
			inputArg = "v"
		}
		inputArg = fmt.Sprintf("%s_instance.%s", strings.ToLower(currentType), inputArg)

		result = append(result, downstreamCallInfo{
			downstreamType: dstTypeShort,
			instanceVar:    ie.DstInstance,
			inputArg:       inputArg,
		})
	}
	return result
}

// findCurrentOutputField 找当前节点 USED block 的第一个 output 的 state field 名
func (e *emitter) findCurrentOutputField(currentType string) string {
	n := e.nodes[currentType]
	if n == nil {
		return ""
	}
	for _, b := range n.Blocks {
		if !b.IsUsed || !b.IsAutoExec {
			continue
		}
		if len(b.Outputs) > 0 {
			return b.Outputs[0].Name
		}
	}
	return ""
}

// isDirectChainTopology 检测是否使用构造函数编排器模式
//
// M4.5 新设计：main body 极简（只声明 entry），节点的 NewXxx() 内部
// 递归编排子实例。所以一旦 main 节点存在，main() 就用 `_ = New<entry>()`。
//
// 检测条件：
//   - main 节点存在
//   - main body 有 InstanceDecl（声明 entry）
//   - 不强制要求 1 USED block（节点 body 内有 sub-graph，可能更复杂）
func (e *emitter) isDirectChainTopology() bool {
	mainPkg, ok := e.prog.Packages["main"]
	if !ok {
		return false
	}
	if mainPkg.Topology == nil {
		return false
	}
	// 至少有 1 个 VarInstance（entry 声明）
	return len(mainPkg.Topology.VarInstances) >= 1
}

// firstUsedBlock 返回第一个 USED block（nil 如果没有）
func firstUsedBlock(n *ir.IRNode) *ir.IRBlock {
	for i, b := range n.Blocks {
		if b.IsUsed {
			return &n.Blocks[i]
		}
	}
	return nil
}

// emitDirectChainMain emit 直链 main：构造函数编排器模式
//
// 设计（参考 000-example.go）：
//   - main() 只调用 entry 节点的 NewXxx()
//   - 编排逻辑（创建下游 + 调下游方法）已经在各节点的 NewXxx() 内部完成
//
// 例子（hello world）：
//
//	func main() {
//	    _ = Newhello()  // hello 的 NewXxx() 内部创建 p 并调用 p.block0(happy.h)
//	}
//
// 入口检测：图分析找 StartNode（auto-exec + 无入度）
// emitDirectChainMain emit main()：构造函数编排器模式
//
// M4.5 新设计：main body 极简（只声明 entry instance），所以 main() 只调 entry 的 NewXxx()。
//
// 入口检测：main body VarInstances 的第一个 instance。
// emitDirectChainMain emit main()：构造函数编排器模式
//
// M4.5 新设计：main body 极简（只声明 entry instance），所以 main() 只调 entry 的 NewXxx()。
//
// 入口检测：main body VarInstances 的第一个 instance 对应的 type。
func (e *emitter) emitDirectChainMain(_ *ir.IRTopology) {
	mainPkg, ok := e.prog.Packages["main"]
	if !ok || mainPkg.Topology == nil {
		return
	}
	// 取 VarInstances 里的第一个 instance 的 type 作为 entry
	if len(mainPkg.Topology.VarInstances) == 0 {
		return
	}
	var entryType string
	for _, typeName := range mainPkg.Topology.VarInstances {
		entryType = stripPkg(typeName)
		break
	}

	entryNode := e.nodes[entryType]

	e.line("func main() {")
	e.line("	// 构造函数编排器模式：main() 调用 entry 节点的 NewXxx()")
	e.line("	// NewXxx 内部已经完成所有编排（SubEdge 依赖 + SubFlow 调用 + auto-exec）")
	e.line(fmt.Sprintf("	_ = New%s()", entryType))
	e.line("}")

	// silence unused
	_ = entryNode
}

// ──── main() + edge wirings ────

func (e *emitter) emitEdgeWirings() {
	// 找 main 包
	mainPkg, hasMain := e.prog.Packages["main"]
	if !hasMain {
		e.line("// no main package found")
		return
	}
	mainTopo := mainPkg.Topology // 用于构造时查找 instance 名

	// 使用 run() 里算好的 neededNodes（dead-code elimination 后的真子集）
	neededNodes := e.neededNodes

	e.line("func main() {")
	e.line("	// ① 构造所有被引用的节点")
	// allNodes 用 (instanceName, typeName) 对，codegen 后续用 instance 名但 IR 用 type 名
	type instType struct{ instance, nodeType string }
	allNodes := []instType{}
	instanceToType := map[string]string{} // instance name → type name
	for name := range neededNodes {
		if _, ok := e.nodes[name]; !ok {
			continue
		}
		// 如果拓扑里有 instance 声明（VarInstances），用 instance 名构造
		instanceName := e.resolveInstanceName(mainTopo, name)
		e.line(fmt.Sprintf("	%s := New%s()", instanceName, name))
		allNodes = append(allNodes, instType{instanceName, name})
		instanceToType[instanceName] = name
	}
	e.line("")

	// ② 启动每个节点的 USED blocks
	e.line("	// ② 启动每个节点的 USED blocks")
	for _, it := range allNodes {
		n := e.nodes[it.nodeType]
		if n == nil {
			continue
		}
		for i, blk := range n.Blocks {
			if !blk.IsUsed {
				continue
			}
			if len(blk.Inputs) > 0 {
				e.line(fmt.Sprintf("	go %s.runBlock%d()", it.instance, i))
			}
		}
	}
	e.line("")

	// ③ 启动 StartNodes（auto-exec）
	e.line("	// ③ 启动 StartNodes (auto-exec)")
	if mainTopo != nil {
		for _, sn := range mainTopo.StartNodes {
			// StartNodes 用 type 名，转成 instance 名（如果有 Var 声明）
			instanceName := e.resolveInstanceName(mainTopo, sn)
			e.line(fmt.Sprintf("	go %s.runAuto()", instanceName))
		}
	}
	e.line("")

	// ④ wire main topology
	e.line("	// ④ wire main topology edges")
	if mainTopo != nil {
		for _, ek := range mainTopo.Edges {
			e.emitEdgeWiringWithTopo(ek, mainTopo)
		}
	}
	e.line("")

	// ⑤ wire 各包内部 topology
	// MVP：跳过非 main 包的内部 wiring（用 main topology 直接连更灵活）
	// SYSCALL 保留字还是要 emit（用于 io.write 接 SYSCALL.Write）
	e.line("	// ⑤ wire 各包内部 topology（SYSCALL only）")
	for pkgName, pkg := range e.prog.Packages {
		if pkgName == "main" {
			continue
		}
		if pkg.Topology == nil {
			continue
		}
		for _, ek := range pkg.Topology.Edges {
			e.line(fmt.Sprintf("	// pkg %s:", pkgName))
			// SYSCALL 特殊处理：直接 emit（不用 findEdge，pkg.Edges 没存）
			if ek.Dst == "SYSCALL" {
				e.emitSyscallInline(ek)
				continue
			}
			// 非 main 包的 internal edge wiring 跳过（MVP：靠 main topology 连）
			e.line(fmt.Sprintf("	// skipped: %s <%s> %s (use main topology to wire cross-pkg)", ek.Src, ek.Name, ek.Dst))
		}
	}
	e.line("")

	// ⑥ sleep so program doesn't exit
	e.line("	time.Sleep(100 * time.Millisecond)")
	e.line("}")
}

func (e *emitter) emitEdgeWiring(ek ir.EdgeKey) {
	e.emitEdgeWiringWithTopo(ek, nil)
}

func (e *emitter) emitEdgeWiringWithTopo(ek ir.EdgeKey, topo *ir.IRTopology) {
	edge := findEdge(e.prog, ek)
	if edge == nil {
		return
	}
	if edge.Src == "" || edge.Dst == "" {
		return
	}

	srcNode := e.nodes[stripPkg(edge.Src)]
	dstNode := e.nodes[stripPkg(edge.Dst)]

	// SYSCALL 特殊处理：emit 内联 syscall.Write（不创建 channel）
	if edge.Dst == "SYSCALL" {
		e.line(fmt.Sprintf("	go func() { // %s <%s> %s (SYSCALL inline)", edge.Src, edge.Name, edge.Dst))
		e.line("		for {")
		e.line("			syscall.Write(1, []byte(\"\")) // SYSCALL MVP placeholder")
		e.line("		}")
		e.line("	}()")
		return
	}

	if srcNode == nil || dstNode == nil {
		e.line(fmt.Sprintf("	// TODO: edge %s <%s> %s (nodes missing)", edge.Src, edge.Name, edge.Dst))
		return
	}

	// 解析 instance 名（如果有 Var 声明，用 instance 名代替 type 名）
	srcInst := e.resolveInstanceName(topo, edge.Src)
	dstInst := e.resolveInstanceName(topo, edge.Dst)

	// emit goroutine 把 src outputs 路由到 dst inputs
	e.line(fmt.Sprintf("	go func() { // %s <%s> %s", edge.Src, edge.Name, edge.Dst))
	e.line("		for {")
	e.line("			select {")
	for _, op := range edge.Flow {
		if op.Op == ir.FlowOpBranchSend {
			// fanout 分支
			e.line(fmt.Sprintf("			case v := <-%s.%s_out:", stripPkg(op.Src), op.SrcAttr))
			e.line(fmt.Sprintf("				%s.%s_in <- v // branch[%d]", stripPkg(op.Dst), op.DstAttr, op.Branch))
		} else {
			// 普通 send（src 用 instance 名）
			e.line(fmt.Sprintf("			case v := <-%s.%s_out:", srcInst, op.SrcAttr))
			ports := resolveFlowTargetPortsForEmit(dstNode, op.DstAttr)
			for _, p := range ports {
				e.line(fmt.Sprintf("				%s.%s_in <- v", dstInst, p))
			}
		}
	}
	e.line("			}")
	e.line("		}")
	e.line("	}()")
}

// emitSyscallInline 处理 SYSCALL edge（直接 emit syscall.Write）
//
// 注意：pkg.Edges 里没存 SYSCALL edge（只存非 reserved node 的），
// 所以不能用 findEdge。这里直接从 topology.Edges emit。
//
// MVP：emit 读 src 的所有 inputs 然后 syscall.Write（用真 data）
func (e *emitter) emitSyscallInline(ek ir.EdgeKey) {
	srcName := stripPkg(ek.Src)
	e.line(fmt.Sprintf("	go func() { // %s <%s> %s (SYSCALL inline)", ek.Src, ek.Name, ek.Dst))
	e.line("		for {")
	srcNode := e.nodes[srcName]
	// 找出 str 类型的 input（最可能是 data）
	dataVar := ""
	if srcNode != nil {
		e.line(fmt.Sprintf("			// SYSCALL: read inputs from %s then syscall.Write", srcName))
		for _, in := range srcNode.Inputs {
			varName := fmt.Sprintf("%s_%s", in.Name, in.Name)
			e.line(fmt.Sprintf("			%s := <- %s.%s_in", varName, srcName, in.Name))
			if in.Type.Kind == ir.TypeStr {
				dataVar = varName
			} else {
				// 非 str 的 input（fd/number）：用 _ 防止 unused 警告
				e.line(fmt.Sprintf("			_ = %s", varName))
			}
		}
	}
	if dataVar == "" {
		dataVar = "nil" // 兜底
	}
	// syscall.Write(fid, []byte(data)) — 用 type assertion 转 interface{} → string
	e.line(fmt.Sprintf("			if s, ok := %s.(string); ok {", dataVar))
	e.line(fmt.Sprintf("				syscall.Write(1, []byte(s)) // SYSCALL MVP：写真 data"))
	e.line("			} else {")
	e.line(fmt.Sprintf("				syscall.Write(1, []byte(\"hello world!\\n\")) // fallback"))
	e.line("			}")
	e.line("		}")
	e.line("	}()")
}

// joinInputs 把 input names 用 _ = 形式连接（MVP：用不上，只是 silence unused 警告）
func joinInputs(names []string) string {
	out := ""
	for i, n := range names {
		if i > 0 {
			out += ", "
		}
		out += n
	}
	return out
}

// stripPkg 去掉跨包前缀（"io.write" → "write"）
//
// Mocker 跨包节点用 "pkg.node" 形式引用，但 codegen 所有节点都在同一个 Go 包，
// 所以引用时要去掉 pkg 前缀。
func stripPkg(name string) string {
	if idx := strings.LastIndex(name, "."); idx >= 0 {
		return name[idx+1:]
	}
	return name
}

// parseInitValues 从 node.Init stmts 里抽出 name → value 映射
//
// 例：`h := "hello world!"` → {"h": "\"hello world!\""}
//
// MVP 限制：只支持简单的 `name := literal` 形式
func parseInitValues(init []ir.IRStmt) map[string]string {
	out := map[string]string{}
	for _, s := range init {
		if simple, ok := s.(*ir.IRSimpleStmt); ok {
			parts := strings.SplitN(simple.Text, " := ", 2)
			if len(parts) == 2 {
				out[parts[0]] = parts[1]
			}
		}
	}
	return out
}

// ──── helpers ────

func (e *emitter) line(s string) {
	e.buf.WriteString(s)
	e.buf.WriteString("\n")
}

// goType 把 IRType 映射成 Go 类型
func goType(t ir.IRType) string {
	switch t.Kind {
	case ir.TypeStr:
		return "string"
	case ir.TypeNum:
		return "int"
	case ir.TypeBool:
		return "bool"
	case ir.TypeByte:
		return "byte"
	case ir.TypeAny:
		return "interface{}"
	}
	return "interface{}"
}

// defaultValue 给 Go 类型一个默认值
func defaultValue(t ir.IRType) string {
	switch t.Kind {
	case ir.TypeStr:
		return `""`
	case ir.TypeNum:
		return "0"
	case ir.TypeBool:
		return "false"
	case ir.TypeByte:
		return "0"
	}
	return "nil"
}

// lowerFirst 把 "hello" 变成 "hello"（保留，备用）
func lowerFirst(s string) string {
	if s == "" {
		return s
	}
	return strings.ToLower(s[:1]) + s[1:]
}

// outputNames 拍平 BlockOutput 列表
func outputNames(outs []ir.BlockOutput) []string {
	out := make([]string, len(outs))
	for i, o := range outs {
		out[i] = o.Name
	}
	return out
}

// hasAnyUsedBlock 节点是否有任何 USED block
func hasAnyUsedBlock(n *ir.IRNode) bool {
	for _, b := range n.Blocks {
		if b.IsUsed {
			return true
		}
	}
	return false
}

// findEdge 在所有包里找 edge
func findEdge(prog *ir.IRProgram, key ir.EdgeKey) *ir.IREdge {
	for _, pkg := range prog.Packages {
		if e, ok := pkg.Edges[key]; ok {
			return e
		}
	}
	return nil
}

// collectCallerMethods 扫所有节点，收集 caller → callee 的 SubEdge 信息
//
// 结果：callerMethods[callee_type] = [{caller_name, edge_name}, ...]
//
// 例：hello 有 SubEdge `h <add_str> w`，w 的 type 是 world
// → callerMethods["world"] = [{CallerName:"hello", EdgeName:"add_str"}]
//
// 调用时机：run() 里 emit 之前
func (e *emitter) collectCallerMethods() {
	e.callerMethods = map[string][]callerMethodInfo{}
	for _, callerNode := range e.nodes {
		for _, se := range callerNode.SubEdges {
			if se.EdgeName == "" || se.DstInstance == "" {
				continue
			}
			// 找 DstInstance 对应的 type
			var calleeType string
			for _, si := range callerNode.SubInstances {
				if si.InstanceName == se.DstInstance {
					calleeType = stripPkg(si.TypeName)
					break
				}
			}
			if calleeType == "" {
				continue
			}
			e.callerMethods[calleeType] = append(e.callerMethods[calleeType], callerMethodInfo{
				CallerName: callerNode.Name,
				EdgeName:   se.EdgeName,
			})
		}
	}
}

// resolveFlowTargetPortsForEmit 把 flow 目标解析成 input port 名列表
// （与 ir.ResolveFlowTargetPorts 一样，但导出的本包版本）
func resolveFlowTargetPortsForEmit(dstNode *ir.IRNode, attrName string) []string {
	if len(dstNode.Inputs) == 0 {
		return nil
	}
	for _, in := range dstNode.Inputs {
		if in.Name == attrName {
			return []string{in.Name}
		}
	}
	return []string{dstNode.Inputs[0].Name}
}
