// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ide} from '../models';
import {context} from '../models';

export function ApplyEdit(arg1:ide.Edit):Promise<ide.GraphData>;

export function BuildGraph():Promise<ide.GraphData>;

export function Compile(arg1:ide.CompileOptions):Promise<ide.CompileResult>;

export function GetWorkspace():Promise<string>;

export function InspectNode(arg1:string):Promise<ide.IRNodeState>;

export function LoadFile(arg1:string):Promise<string>;

export function LocateNode(arg1:string):Promise<ide.NodeLocation>;

export function OpenWorkspace(arg1:string):Promise<ide.WorkspaceInfo>;

export function ParseFile(arg1:string):Promise<ide.ParsedFile>;

export function ParseSource(arg1:string):Promise<ide.ParsedFile>;

export function ParseWorkspace():Promise<ide.ParsedFile>;

export function ReparseWorkspace(arg1:string,arg2:string):Promise<ide.WorkspaceInfo>;

export function Run(arg1:ide.CompileOptions):Promise<any>;

export function SaveFile(arg1:string,arg2:string):Promise<void>;

export function SerializeToSource():Promise<string>;

export function SetContext(arg1:context.Context):Promise<void>;

export function SetWorkspace(arg1:string):Promise<void>;

export function Version():Promise<ide.VersionInfo>;
