// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyEdit(arg1) {
  return window['go']['ide']['Service']['ApplyEdit'](arg1);
}

export function BuildGraph() {
  return window['go']['ide']['Service']['BuildGraph']();
}

export function Compile(arg1) {
  return window['go']['ide']['Service']['Compile'](arg1);
}

export function GetWorkspace() {
  return window['go']['ide']['Service']['GetWorkspace']();
}

export function InspectNode(arg1) {
  return window['go']['ide']['Service']['InspectNode'](arg1);
}

export function LoadFile(arg1) {
  return window['go']['ide']['Service']['LoadFile'](arg1);
}

export function LocateNode(arg1) {
  return window['go']['ide']['Service']['LocateNode'](arg1);
}

export function OpenWorkspace(arg1) {
  return window['go']['ide']['Service']['OpenWorkspace'](arg1);
}

export function ParseFile(arg1) {
  return window['go']['ide']['Service']['ParseFile'](arg1);
}

export function ParseSource(arg1) {
  return window['go']['ide']['Service']['ParseSource'](arg1);
}

export function ParseWorkspace() {
  return window['go']['ide']['Service']['ParseWorkspace']();
}

export function ReparseWorkspace(arg1, arg2) {
  return window['go']['ide']['Service']['ReparseWorkspace'](arg1, arg2);
}

export function Run(arg1) {
  return window['go']['ide']['Service']['Run'](arg1);
}

export function SaveFile(arg1, arg2) {
  return window['go']['ide']['Service']['SaveFile'](arg1, arg2);
}

export function SerializeToSource() {
  return window['go']['ide']['Service']['SerializeToSource']();
}

export function SetContext(arg1) {
  return window['go']['ide']['Service']['SetContext'](arg1);
}

export function SetWorkspace(arg1) {
  return window['go']['ide']['Service']['SetWorkspace'](arg1);
}

export function Version() {
  return window['go']['ide']['Service']['Version']();
}
