// Package d2gen 从 Mocker IR 生成 d2 图表脚本
//
// 设计目标：**聚焦节点之间的关系和边**，不画 inputs/outputs/state 等内部细节。
//
// 生成的 d2 脚本：
//   - 每个 IRNode → 一个 d2 节点（圆形/矩形）
//   - SubEdge → 箭头（带 edge name 标签）
//   - SubFlow → 箭头（带 ">>" 标签）
//   - 顶层 Edge body → 箭头（带 edge name 标签）
//   - SYSCALL → 云形节点
//   - main entry → 绿色六边形
//
// 双向边优化：
//   - 如果 top-level edge 的 Flow 中有反向流（dst→src），使用 `<->` 箭头
//   - 如果 SubEdge/SubFlow 在两个方向上都有连接（A→B 和 B→A），合并为 `<->` 箭头
//
// 示例输出：
//
//	direction: right
//	main_entry -> hello: "entry"
//	hello <-> world: "<add_str>"
//	hello -> Println: ">>"
//	Println -> write: ">>"
//	write -> SYSCALL: "syscall"
//	hello: hello { ... }
//	world: world { ... }
package d2gen

import (
	"fmt"
	"sort"
	"strings"

	"circle/internal/ir"
)

// Options 控制 d2 图生成
type Options struct {
	// Direction 全局方向：down / right / left / up（默认 right，适合数据流从左到右）
	Direction string

	// IncludePackages 只包含指定 package（空 = 全部）
	IncludePackages map[string]bool
}

// edgePair 归一化的节点对（lo < hi），用于双向检测
type edgePair struct{ lo, hi string }

// rawEdge 一条待输出的原始边
type rawEdge struct {
	src   string
	dst   string
	label string
}

// Generate 从 IRProgram 生成 d2 脚本
//
// 聚焦节点之间的连线，忽略 inputs/outputs/state 等内部细节。
func Generate(prog *ir.IRProgram, opts *Options) string {
	if opts == nil {
		opts = &Options{}
	}
	if opts.Direction == "" {
		opts.Direction = "right"
	}

	// 只保留从 main entry 可达的节点
	used := findReachableNodes(prog)

	var sb strings.Builder

	sb.WriteString("# Auto-generated by Mocker circle — IR → d2\n")
	sb.WriteString(fmt.Sprintf("direction: %s\n\n", opts.Direction))

	// ──── 第一部分：连线 ────

	// Phase 1: 预扫描所有 top-level edges，标记双向的 (src,dst) 对
	//
	// 注意：使用 pkg.Edges（map）而不是 pkg.Topology.Edges（slice），
	// 因为 package-level edge 可能在 Topology.Edges 里没列。
	topLevelBidir := map[edgePair]bool{}
	topLevelEdgeName := map[edgePair]string{}
	for _, pkg := range prog.Packages {
		for ek, edge := range pkg.Edges {
			if edge == nil {
				continue
			}
			src := stripPkg(ek.Src)
			dst := stripPkg(ek.Dst)
			if dst == "SYSCALL" || src == "SYSCALL" {
				continue
			}
			// 检查 edge.Flow 中是否有反向流（dst → src）
			for _, op := range edge.Flow {
				if op.Src == ek.Dst && op.Dst == ek.Src {
					lo, hi := src, dst
					if lo > hi {
						lo, hi = hi, lo
					}
					topLevelBidir[edgePair{lo, hi}] = true
					topLevelEdgeName[edgePair{lo, hi}] = ek.Name
					break
				}
			}
		}
	}

	// Phase 2: 收集所有边
	var edges []rawEdge

	// main entry → entry node
	if mainPkg, ok := prog.Packages["main"]; ok && mainPkg.Topology != nil {
		for _, typ := range mainPkg.Topology.VarInstances {
			entryType := stripPkg(typ)
			edges = append(edges, rawEdge{src: "main_entry", dst: entryType, label: ""})
		}
	}

	// SubEdge + SubFlow（节点 body 内的 sub-graph）
	for _, n := range prog.AllNodes() {
		if n.Name == "main" {
			continue
		}
		if !used[n.Name] {
			continue
		}
		if opts.IncludePackages != nil && !opts.IncludePackages[n.PkgName()] {
			continue
		}
		for _, se := range n.SubEdges {
			calleeType := findSubInstanceType(n, se.DstInstance)
			if calleeType == "" || calleeType == "SYSCALL" {
				continue
			}
			// 如果对应 top-level edge 已标记为双向，跳过（由 top-level 统一输出）
			lo, hi := n.Name, calleeType
			if lo > hi {
				lo, hi = hi, lo
			}
			if topLevelBidir[edgePair{lo, hi}] {
				continue
			}
			label := se.EdgeName
			if label == "" {
				label = "sub-edge"
			}
			edges = append(edges, rawEdge{src: n.Name, dst: calleeType, label: "<" + label + ">"})
		}
		for _, sf := range n.SubFlows {
			calleeType := findSubInstanceType(n, sf.DstInstance)
			if calleeType == "" || calleeType == "SYSCALL" {
				continue
			}
			edges = append(edges, rawEdge{src: n.Name, dst: calleeType, label: ">>"})
		}
	}

	// Top-level edges（用 pkg.Edges map 而不是 Topology.Edges slice）
	for _, pkg := range prog.Packages {
		for ek, edge := range pkg.Edges {
			if edge == nil {
				continue
			}
			src := stripPkg(ek.Src)
			dst := stripPkg(ek.Dst)
			if dst == "SYSCALL" {
				edges = append(edges, rawEdge{src: src, dst: "SYSCALL", label: "syscall"})
			} else {
				lo, hi := src, dst
				if lo > hi {
					lo, hi = hi, lo
				}
				if topLevelBidir[edgePair{lo, hi}] {
					edges = append(edges, rawEdge{src: src, dst: dst, label: "<" + ek.Name + "> (bidir)"})
				} else {
					edges = append(edges, rawEdge{src: src, dst: dst, label: "<" + ek.Name + ">"})
				}
			}
		}
	}

	// Phase 3: 检测 SubEdge/SubFlow 的双向对（A→B 和 B→A 都存在）
	type dirEdge struct {
		src, dst, label string
	}
	dirEdges := map[edgePair][]dirEdge{}
	for _, e := range edges {
		if e.src == "main_entry" || e.dst == "main_entry" {
			continue
		}
		if e.src == "SYSCALL" || e.dst == "SYSCALL" {
			continue
		}
		if strings.Contains(e.label, "(bidir)") {
			continue
		}
		lo, hi := e.src, e.dst
		if lo > hi {
			lo, hi = hi, lo
		}
		dirEdges[edgePair{lo, hi}] = append(dirEdges[edgePair{lo, hi}], dirEdge{src: e.src, dst: e.dst, label: e.label})
	}

	bidirSubPairs := map[edgePair]bool{}
	for k, es := range dirEdges {
		forward := false
		backward := false
		for _, e := range es {
			if e.src == k.lo && e.dst == k.hi {
				forward = true
			} else {
				backward = true
			}
		}
		if forward && backward {
			bidirSubPairs[k] = true
		}
	}

	// Phase 4: 去重 + 输出
	sb.WriteString("# === Connections ===\n\n")
	seenEdges := map[string]bool{}
	for _, e := range edges {
		lo, hi := e.src, e.dst
		if lo > hi {
			lo, hi = hi, lo
		}
		pair := edgePair{lo, hi}

		// 双向 top-level edge → <->
		if strings.Contains(e.label, "(bidir)") && !seenEdges["bidir:"+lo+":"+hi] {
			edgeName := topLevelEdgeName[pair]
			if edgeName == "" {
				edgeName = "<>"
			}
			sb.WriteString(fmt.Sprintf("%s <-> %s: \"<%s>\"\n", lo, hi, edgeName))
			seenEdges["bidir:"+lo+":"+hi] = true
			continue
		}
		if strings.Contains(e.label, "(bidir)") {
			continue
		}

		// 双向 SubEdge/SubFlow 对 → 合并为 <->
		if bidirSubPairs[pair] && !seenEdges["subbidir:"+lo+":"+hi] {
			var labels []string
			for _, de := range dirEdges[pair] {
				if de.label != "" {
					labels = append(labels, de.label)
				}
			}
			labels = unique(labels)
			mergedLabel := strings.Join(labels, " / ")
			if mergedLabel == "" {
				mergedLabel = ">>"
			}
			sb.WriteString(fmt.Sprintf("%s <-> %s: \"%s\"\n", lo, hi, mergedLabel))
			seenEdges["subbidir:"+lo+":"+hi] = true
			continue
		}
		if bidirSubPairs[pair] {
			continue
		}

		// 普通单向边（去重）
		normKey := e.src + " -> " + e.dst
		if e.src == "main_entry" || e.dst == "SYSCALL" {
			// main_entry 和 SYSCALL 不参与去重
		} else if seenEdges[normKey] {
			continue
		}
		seenEdges[normKey] = true
		if e.label == "" {
			sb.WriteString(fmt.Sprintf("%s -> %s\n", e.src, e.dst))
		} else {
			sb.WriteString(fmt.Sprintf("%s -> %s: \"%s\"\n", e.src, e.dst, e.label))
		}
	}

	// ──── 第二部分：节点定义（给 d2 渲染用）────
	sb.WriteString("\n# === Nodes ===\n\n")

	// SYSCALL 保留字节点（如果有）
	hasSyscall := false
	for _, pkg := range prog.Packages {
		for ek := range pkg.Edges {
			if ek.Dst == "SYSCALL" {
				hasSyscall = true
			}
		}
	}
	if hasSyscall {
		sb.WriteString("SYSCALL: SYSCALL {\n")
		sb.WriteString("  shape: cloud\n")
		sb.WriteString("  style.fill: \"#fee\"\n")
		sb.WriteString("  style.stroke: \"#c00\"\n")
		sb.WriteString("}\n\n")
	}

	// main entry（绿色六边形）
	if mainPkg, ok := prog.Packages["main"]; ok && mainPkg.Topology != nil {
		sb.WriteString("main_entry: main {\n")
		sb.WriteString("  shape: hexagon\n")
		sb.WriteString("  style.fill: \"#e7f5e7\"\n")
		sb.WriteString("  style.stroke: \"#0a0\"\n")
		sb.WriteString("  style.font-size: 24\n")
		sb.WriteString("}\n\n")
		for inst, typ := range mainPkg.Topology.VarInstances {
			sb.WriteString(fmt.Sprintf("# entry instance: %s → %s\n", inst, stripPkg(typ)))
		}
		sb.WriteString("\n")
	}

	// 所有节点（按名字排序，确保输出稳定）
	nodeNames := sortedNodeNames(prog.AllNodes())
	for _, name := range nodeNames {
		if name == "main" {
			continue
		}
		if !used[name] {
			continue
		}
		n := prog.AllNodes()[name]
		if opts.IncludePackages != nil && !opts.IncludePackages[n.PkgName()] {
			continue
		}
		writeNodeDef(&sb, n)
	}

	return sb.String()
}

// writeNodeDef 写节点定义（只含名字 + 可选 shape/样式）
func writeNodeDef(sb *strings.Builder, n *ir.IRNode) {
	sb.WriteString(fmt.Sprintf("%s: %s {\n", n.Name, n.Name))
	sb.WriteString("  shape: class\n")
	sb.WriteString("  style.font-size: 20\n")
	if n.PkgName() != "main" {
		sb.WriteString(fmt.Sprintf("  # package: %s\n", n.PkgName()))
	}
	sb.WriteString("}\n\n")
}

// findSubInstanceType 找 sub-instance 对应的节点类型名（strip pkg 前缀）
func findSubInstanceType(n *ir.IRNode, instanceName string) string {
	for _, si := range n.SubInstances {
		if si.InstanceName == instanceName {
			return stripPkg(si.TypeName)
		}
	}
	if instanceName == "SYSCALL" {
		return "SYSCALL"
	}
	return ""
}

// stripPkg 去掉跨包前缀（"io.write" → "write"）
func stripPkg(name string) string {
	if idx := strings.LastIndex(name, "."); idx >= 0 {
		return name[idx+1:]
	}
	return name
}

// sortedNodeNames 按名字排序 node map
func sortedNodeNames(m map[string]*ir.IRNode) []string {
	names := make([]string, 0, len(m))
	for name := range m {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

// unique 去重字符串切片（保持顺序）
func unique(ss []string) []string {
	seen := map[string]bool{}
	var out []string
	for _, s := range ss {
		if !seen[s] {
			seen[s] = true
			out = append(out, s)
		}
	}
	return out
}

// findReachableNodes 从 main entry BFS 找出所有可达节点
func findReachableNodes(prog *ir.IRProgram) map[string]bool {
	used := map[string]bool{}
	var queue []string

	// 起点：main Topology VarInstances
	for _, pkg := range prog.Packages {
		if pkg.Topology == nil {
			continue
		}
		for _, typeName := range pkg.Topology.VarInstances {
			n := stripPkg(typeName)
			if !used[n] {
				used[n] = true
				queue = append(queue, n)
			}
		}
	}

	// BFS
	for len(queue) > 0 {
		cur := queue[0]
		queue = queue[1:]
		node := prog.FindNodeByName(cur)
		if node == nil {
			continue
		}
		for _, si := range node.SubInstances {
			n := stripPkg(si.TypeName)
			if !used[n] {
				used[n] = true
				queue = append(queue, n)
			}
		}
	}

	return used
}
